set -g default-shell /bin/bash
set -gu default-command

unbind C-b
set -g prefix \`
bind \` send-prefix

set -g default-terminal "tmux-256color"
set -g history-limit 100000
set -g mode-keys vi
set -g xterm-keys on

set -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_CONNECTION SSH_TTY LANG LC_ALL LC_CTYPE COLORTERM SHELL"

bind ] split-window -h -c "#{pane_current_path}"
bind = split-window -v -c "#{pane_current_path}"

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi Home send-keys -X start-of-line
bind -T copy-mode-vi End  send-keys -X end-of-line

bind Left  select-pane -L
bind Right select-pane -R
bind Up    select-pane -U
bind Down  select-pane -D

unbind '"'
unbind %
unbind q
bind q copy-mode

set -g mouse on
bind Enter resize-pane -Z

bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

set -g status-bg "default"
set -g status-fg "default"
set -g window-style "default"
set -g window-active-style "default"

unbind C-n
bind -n C-n new-window
unbind C-PageUp
unbind C-PageDown
bind -n C-PageUp previous-window
bind -n C-PageDown next-window
bind -n F12 detach