# Dependabot configuration
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/blockchain"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/web/frontend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/web/backend"
    schedule:
      interval: "monthly"
