moniker = "${MONIKER}"

[rpc]
laddr = "tcp://0.0.0.0:26657"
cors_allowed_origins = ["*"]

[p2p]
laddr = "tcp://0.0.0.0:26656"
addr_book_strict = false
pex = ${PEX_ENABLED}
persistent_peers = "${PERSISTENT_PEERS}"
max_num_inbound_peers = ${MAX_INBOUND_PEERS}
max_num_outbound_peers = ${MAX_OUTBOUND_PEERS}

[consensus]
create_empty_blocks = false
create_empty_blocks_interval = "600s"
timeout_commit = "3s"


