moniker = "${MONIKER}"
db_backend = "${COMET_DB_BACKEND:-goleveldb}"

[tx_index]
indexer = "kv"

[rpc]
laddr = "tcp://0.0.0.0:26657"
cors_allowed_origins = ["*"]

[p2p]
laddr = "tcp://0.0.0.0:26656"
addr_book_strict = false
pex = ${PEX_ENABLED}
persistent_peers = "${PERSISTENT_PEERS}"
max_num_inbound_peers = ${MAX_INBOUND_PEERS}
max_num_outbound_peers = ${MAX_OUTBOUND_PEERS}

[consensus]
create_empty_blocks = ${CREATE_EMPTY_BLOCKS:-false}
create_empty_blocks_interval = "${CREATE_EMPTY_BLOCKS_INTERVAL:-600s}"
timeout_commit = "${TIMEOUT_COMMIT:-3s}"

[statesync]
enable = ${STATESYNC_ENABLE:-false}
rpc_servers = "${STATESYNC_RPC_SERVERS:-}"
trust_height = ${STATESYNC_TRUST_HEIGHT:-0}
trust_hash = "${STATESYNC_TRUST_HASH:-}"
trust_period = "168h0m0s"


