const onyxDarkColors = {
    bg: '#141414',
    text: '#E0E0E0',
    subtleText: '#999',
    card: '#1E1E1E',
    panel: '#1E1E1E',
    panelAlt: '#282828',
    border: '#333',
    accent: '#303030',
    accentHover: '#3A3A3A',
    accentDisabled: '#444',
    buttonText: '#E0E0E0',
    link: '#E0E0E0',
    linkHover: '#BBB',
    scrollbar: '#555',
    cardAlt: '#242424',
    cardBorder: '#333',
    sidebarBg: '#1A1A1A',
    headerBg: '#1A1A1A',

    surface: '#1E1E1E',
    surface2: '#282828',
    surface3: '#333',
    borderSubtle: '#2A2A2A',
    borderStrong: '#555',
    textSecondary: '#999',
    inputBackground: '#242424',
    accentSubtle: '#1E1E1E',
    cardHoverBorder: '#555',

    voteUp: '#16a34a',
    voteUpHover: '#22c55e',
    voteUpBg: 'rgba(22, 163, 74, 0.14)',
    voteDown: '#dc2626',
    voteDownHover: '#ef4444',
    voteDownBg: 'rgba(220, 38, 38, 0.14)',
    overlay: 'rgba(0, 0, 0, 0.7)',
    cardShadow: 'none',
    cardShadowHover: 'none',

    success: '#22c55e',
    successBg: 'rgba(34, 197, 94, 0.1)',
    successBorder: 'rgba(34, 197, 94, 0.3)',
    warning: '#eab308',
    warningBg: 'rgba(234, 179, 8, 0.1)',
    warningBorder: 'rgba(234, 179, 8, 0.3)',
    danger: '#ef4444',
    dangerBg: 'rgba(239, 68, 68, 0.1)',
    dangerBorder: 'rgba(239, 68, 68, 0.3)',
    muted: '#666',
    focusBorder: '#888',

    inboxReplyUnreadBg: 'rgba(255, 255, 255, 0.06)',
    inboxReplyReadBg: 'rgba(255, 255, 255, 0.03)',
    inboxReplyUnreadBorder: 'rgba(255, 255, 255, 0.15)',
    inboxReplyReadBorder: 'rgba(255, 255, 255, 0.06)',
    inboxReplyUnreadBgHover: 'rgba(255, 255, 255, 0.09)',
    inboxReplyReadBgHover: 'rgba(255, 255, 255, 0.05)',
};

const onyxLightColors = {
    bg: '#FAFAFA',
    text: '#111',
    subtleText: '#555',
    card: '#FFFFFF',
    panel: '#F5F5F5',
    panelAlt: '#EBEBEB',
    border: '#D0D0D0',
    accent: '#E0E0E0',
    accentHover: '#D0D0D0',
    accentDisabled: '#F0F0F0',
    buttonText: '#111',
    link: '#111',
    linkHover: '#333',
    scrollbar: '#AAA',
    cardAlt: '#F0F0F0',
    cardBorder: '#D0D0D0',
    sidebarBg: '#F5F5F5',
    headerBg: '#F5F5F5',

    surface: '#F5F5F5',
    surface2: '#EBEBEB',
    surface3: '#E0E0E0',
    borderSubtle: '#E0E0E0',
    borderStrong: '#BBB',
    textSecondary: '#555',
    inputBackground: '#FFFFFF',
    accentSubtle: '#F5F5F5',
    cardHoverBorder: '#BBB',

    voteUp: '#16a34a',
    voteUpHover: '#15803d',
    voteUpBg: 'rgba(22, 163, 74, 0.12)',
    voteDown: '#dc2626',
    voteDownHover: '#b91c1c',
    voteDownBg: 'rgba(220, 38, 38, 0.12)',
    overlay: 'rgba(0, 0, 0, 0.5)',
    cardShadow: '0 1px 3px rgba(0, 0, 0, 0.08)',
    cardShadowHover: '0 2px 6px rgba(0, 0, 0, 0.1)',

    success: '#16a34a',
    successBg: 'rgba(22, 163, 74, 0.08)',
    successBorder: 'rgba(22, 163, 74, 0.25)',
    warning: '#ca8a04',
    warningBg: 'rgba(202, 138, 4, 0.08)',
    warningBorder: 'rgba(202, 138, 4, 0.25)',
    danger: '#dc2626',
    dangerBg: 'rgba(220, 38, 38, 0.08)',
    dangerBorder: 'rgba(220, 38, 38, 0.25)',
    muted: '#888',
    focusBorder: '#666',

    inboxReplyUnreadBg: 'rgba(0, 0, 0, 0.04)',
    inboxReplyReadBg: 'rgba(0, 0, 0, 0.02)',
    inboxReplyUnreadBorder: 'rgba(0, 0, 0, 0.1)',
    inboxReplyReadBorder: 'rgba(0, 0, 0, 0.04)',
    inboxReplyUnreadBgHover: 'rgba(0, 0, 0, 0.06)',
    inboxReplyReadBgHover: 'rgba(0, 0, 0, 0.04)',
};

function buildLayout(colors) {
    return {
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans', sans-serif",
        formRowColumns: 'minmax(140px, 220px) minmax(0, 1fr)',
        formRowGap: '0.5rem',
        formRowMargin: '0.4rem 0',
        formRowAlign: 'start',

        labelSize: '0.85rem',
        labelWeight: '600',
        labelPaddingTop: '0.7rem',

        containerBg: colors.panelAlt,
        containerBorder: `1px solid ${colors.border}`,
        containerBorderBottom: null,
        containerRadius: '6px',
        containerPadding: '0.75rem 1rem',
        containerPaddingCompact: '0.6rem 0.85rem',

        inputRadius: '4px',
        inputPadding: '0.5rem 0.75rem',
        inputSize: '0.85rem',
        focusRing: `0 0 0 1px ${colors.focusBorder}`,

        buttonRadius: '4px',
        buttonPadding: '0.45rem 0.85rem',
        buttonSize: '0.75rem',

        bodySize: '0.85rem',
        smallSize: '0.75rem',
        tinySize: '0.65rem',
        monoSize: '0.8rem',

        cardBg: colors.panel,
        cardBorder: `1px solid ${colors.border}`,
        cardBorderBottom: null,
        cardRadius: '6px',
        cardPadding: '0.6rem 0.85rem',
        cardGap: '0.5rem',

        sectionSize: '0.95rem',
        sectionMarginTop: '1.5rem',
        sectionMarginBottom: '0.5rem',

        dividerMargin: '0.75rem 0',

        bannerRadius: '4px',
        bannerPadding: '0.75rem',
        bannerSize: '0.75rem',

        showContainerTab: true,

        containerTabLeft: '1rem',
        containerTabRadius: '4px 4px 0 0',
        containerTabPadding: '0.25rem 0.65rem 0.1rem 0.65rem',
        tabSize: '0.75rem',
        tabWeight: '600',

        contentGridCols: '200px minmax(0, 1fr)',
        contentGridGap: '0.5rem',
        contentMaxWidth: '1600px',
        contentMargin: '0 auto',
        contentPadding: '0 0.5rem',
        contentPaddingTablet: '0 0.25rem',

        feedMaxWidth: 'none',
        feedMargin: '0 auto',
        feedPadding: '0 0.75rem',
        feedGap: 'var(--card-gap, 0.5rem)',
        feedPaddingTablet: '0 0.25rem',
        feedGapTablet: '0.4rem',
        feedGapMobile: 'var(--card-gap-mobile, 0.35rem)',

        tabbedMarginTop: '2.0rem',

        containerBodyBorder: `1px solid ${colors.border}`,
        containerBodyRadius: '8px',
        containerBodyPadding: '1.25rem',
        containerBodyMaxWidth: 'none',
        containerBodyRadiusMobile: '6px',
        containerBodyPaddingMobile: '1rem',

        searchMaxWidth: 'none',
        searchMargin: '0.75rem auto',
        searchPadding: '0 0.75rem',
        searchMarginTablet: '0.5rem auto',
        searchPaddingTablet: '0 0.25rem',
        searchInputPadding: '0.55rem 0.75rem',
        searchInputRadius: '4px',
        searchInputSize: '0.85rem',
        searchFocusShadow: `0 0 0 1px ${colors.focusBorder}`,

        emptyMarginX: '1rem',
        emptyMarginXTablet: '0.25rem',
        emptyPadding: '1.25rem 1rem',
        emptyRadius: '6px',
        emptyTitleSize: '1.1rem',
        emptyTitleMarginBottom: '0.5rem',
        emptyBodySize: '0.75rem',

        errorMarginX: '1rem',
        errorPadding: '0.1rem 0 0.25rem 0',
        errorBorder: 'none',
        errorJustify: 'center',
        errorAlign: 'center',
        errorSize: '1rem',

        voteAreaBg: colors.panel,
        voteAreaBorder: `1px solid ${colors.border}`,
        voteAreaRadius: '6px',
        voteAreaShadow: 'none',
        voteAreaPadding: '8px 6px',
        voteAreaPaddingCompact: '6px 4px',
        voteAreaMarginRight: '0.25rem',
        voteAreaGap: '2px',
        voteAreaGapCompact: '2px',
        voteAreaWidth: '64px',
        voteAreaWidthCompact: '56px',
        voteAreaHeight: '120px',
        voteAreaHeightCompact: '96px',

        voteButtonSize: '32px',
        voteButtonSizeCompact: '28px',
        voteButtonBgInactive: colors.panelAlt,
        voteButtonBorder: `1px solid ${colors.border}`,
        voteButtonRadius: '4px',
        voteButtonHoverTransform: 'none',
        voteIconSize: '16px',

        voteFontSize: '0.95rem',
        voteLineHeight: 'normal',

        tabsRowPosition: 'absolute',
        tabsRowBottom: '100%',
        tabsRowLeft: '1rem',
        tabsRowMarginBottom: '-1px',
        tabsRowGap: '0',
        tabsRowBorderBottom: 'none',
        tabsRowBg: 'transparent',
        tabsRowLeftTablet: '0.5rem',

        clickableTabRadius: '4px 4px 0 0',
        clickableTabPadding: '0.25rem 0.65rem 0.1rem 0.65rem',
        clickableTabPaddingTablet: '0.2rem 0.5rem 0.1rem 0.5rem',
        clickableTabMarginRight: '0.25rem',
        clickableTabTextTransform: 'none',
        clickableTabActiveBorderBottom: 'none',
        clickableTabInactiveBorderBottom: 'none',
        clickableTabShowAfter: true,
        tabSizeTablet: '0.7rem',

        flatMode: true,
        maxVideoWidth: null,
        inboxFullWidth: false,
        profilePostsFullWidth: false,
    };
}

export const dark = {
    name: 'dark',
    themeId: 'onyx',
    colors: onyxDarkColors,
    layout: buildLayout(onyxDarkColors),
};

export const light = {
    name: 'light',
    themeId: 'onyx',
    colors: onyxLightColors,
    layout: buildLayout(onyxLightColors),
};
