// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mirage/core/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProfileCore contains the core scalar fields for a user profile.
// This is the canonical definition used both at genesis and runtime.
type ProfileCore struct {
	Owner              string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Username           string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Level              int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	CreatedAt          int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SubscriptionExpiry int64  `protobuf:"varint,5,opt,name=subscription_expiry,json=subscriptionExpiry,proto3" json:"subscription_expiry,omitempty"`
	AutoRenew          bool   `protobuf:"varint,6,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	ReserveFunds       uint64 `protobuf:"varint,7,opt,name=reserve_funds,json=reserveFunds,proto3" json:"reserve_funds,omitempty"`
	Biography          string `protobuf:"bytes,9,opt,name=biography,proto3" json:"biography,omitempty"`
	Avatar             string `protobuf:"bytes,10,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Banner             string `protobuf:"bytes,11,opt,name=banner,proto3" json:"banner,omitempty"`
	Flair              string `protobuf:"bytes,12,opt,name=flair,proto3" json:"flair,omitempty"`
	EffectivePaid      bool   `protobuf:"varint,13,opt,name=effective_paid,json=effectivePaid,proto3" json:"effective_paid,omitempty"`
}

func (m *ProfileCore) Reset()         { *m = ProfileCore{} }
func (m *ProfileCore) String() string { return proto.CompactTextString(m) }
func (*ProfileCore) ProtoMessage()    {}
func (*ProfileCore) Descriptor() ([]byte, []int) {
	return fileDescriptor_192e6edd9e5d5f9b, []int{0}
}
func (m *ProfileCore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProfileCore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProfileCore.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProfileCore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileCore.Merge(m, src)
}
func (m *ProfileCore) XXX_Size() int {
	return m.Size()
}
func (m *ProfileCore) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileCore.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileCore proto.InternalMessageInfo

func (m *ProfileCore) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ProfileCore) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ProfileCore) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *ProfileCore) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ProfileCore) GetSubscriptionExpiry() int64 {
	if m != nil {
		return m.SubscriptionExpiry
	}
	return 0
}

func (m *ProfileCore) GetAutoRenew() bool {
	if m != nil {
		return m.AutoRenew
	}
	return false
}

func (m *ProfileCore) GetReserveFunds() uint64 {
	if m != nil {
		return m.ReserveFunds
	}
	return 0
}

func (m *ProfileCore) GetBiography() string {
	if m != nil {
		return m.Biography
	}
	return ""
}

func (m *ProfileCore) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *ProfileCore) GetBanner() string {
	if m != nil {
		return m.Banner
	}
	return ""
}

func (m *ProfileCore) GetFlair() string {
	if m != nil {
		return m.Flair
	}
	return ""
}

func (m *ProfileCore) GetEffectivePaid() bool {
	if m != nil {
		return m.EffectivePaid
	}
	return false
}

// InitialProfile is used in genesis to bootstrap profiles.
// It wraps ProfileCore and includes all list fields (stored separately at runtime).
type InitialProfile struct {
	Core               *ProfileCore `protobuf:"bytes,1,opt,name=core,proto3" json:"core,omitempty"`
	FollowedUsers      []string     `protobuf:"bytes,3,rep,name=followed_users,json=followedUsers,proto3" json:"followed_users,omitempty"`
	JoinedCommunities  []string     `protobuf:"bytes,4,rep,name=joined_communities,json=joinedCommunities,proto3" json:"joined_communities,omitempty"`
	BlockedUsers       []string     `protobuf:"bytes,5,rep,name=blocked_users,json=blockedUsers,proto3" json:"blocked_users,omitempty"`
	BlockedPosts       []string     `protobuf:"bytes,6,rep,name=blocked_posts,json=blockedPosts,proto3" json:"blocked_posts,omitempty"`
	BlockedCommunities []string     `protobuf:"bytes,7,rep,name=blocked_communities,json=blockedCommunities,proto3" json:"blocked_communities,omitempty"`
}

func (m *InitialProfile) Reset()         { *m = InitialProfile{} }
func (m *InitialProfile) String() string { return proto.CompactTextString(m) }
func (*InitialProfile) ProtoMessage()    {}
func (*InitialProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_192e6edd9e5d5f9b, []int{1}
}
func (m *InitialProfile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InitialProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InitialProfile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InitialProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialProfile.Merge(m, src)
}
func (m *InitialProfile) XXX_Size() int {
	return m.Size()
}
func (m *InitialProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialProfile.DiscardUnknown(m)
}

var xxx_messageInfo_InitialProfile proto.InternalMessageInfo

func (m *InitialProfile) GetCore() *ProfileCore {
	if m != nil {
		return m.Core
	}
	return nil
}

func (m *InitialProfile) GetFollowedUsers() []string {
	if m != nil {
		return m.FollowedUsers
	}
	return nil
}

func (m *InitialProfile) GetJoinedCommunities() []string {
	if m != nil {
		return m.JoinedCommunities
	}
	return nil
}

func (m *InitialProfile) GetBlockedUsers() []string {
	if m != nil {
		return m.BlockedUsers
	}
	return nil
}

func (m *InitialProfile) GetBlockedPosts() []string {
	if m != nil {
		return m.BlockedPosts
	}
	return nil
}

func (m *InitialProfile) GetBlockedCommunities() []string {
	if m != nil {
		return m.BlockedCommunities
	}
	return nil
}

// RawKVPair stores a single key-value pair from the KV store for generic export/import.
// Keys and values are base64-encoded bytes.
type RawKVPair struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *RawKVPair) Reset()         { *m = RawKVPair{} }
func (m *RawKVPair) String() string { return proto.CompactTextString(m) }
func (*RawKVPair) ProtoMessage()    {}
func (*RawKVPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_192e6edd9e5d5f9b, []int{2}
}
func (m *RawKVPair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RawKVPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RawKVPair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RawKVPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawKVPair.Merge(m, src)
}
func (m *RawKVPair) XXX_Size() int {
	return m.Size()
}
func (m *RawKVPair) XXX_DiscardUnknown() {
	xxx_messageInfo_RawKVPair.DiscardUnknown(m)
}

var xxx_messageInfo_RawKVPair proto.InternalMessageInfo

func (m *RawKVPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RawKVPair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// GenesisState defines the core module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// initial_profiles are profiles to create at genesis (used for bootstrap or backfill)
	InitialProfiles []*InitialProfile `protobuf:"bytes,2,rep,name=initial_profiles,json=initialProfiles,proto3" json:"initial_profiles,omitempty"`
	// raw_state contains ALL key-value pairs from the module's KV store.
	// This is the preferred import method as it preserves complete state.
	RawState []*RawKVPair `protobuf:"bytes,3,rep,name=raw_state,json=rawState,proto3" json:"raw_state,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_192e6edd9e5d5f9b, []int{3}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetInitialProfiles() []*InitialProfile {
	if m != nil {
		return m.InitialProfiles
	}
	return nil
}

func (m *GenesisState) GetRawState() []*RawKVPair {
	if m != nil {
		return m.RawState
	}
	return nil
}

func init() {
	proto.RegisterType((*ProfileCore)(nil), "mirage.core.v1.ProfileCore")
	proto.RegisterType((*InitialProfile)(nil), "mirage.core.v1.InitialProfile")
	proto.RegisterType((*RawKVPair)(nil), "mirage.core.v1.RawKVPair")
	proto.RegisterType((*GenesisState)(nil), "mirage.core.v1.GenesisState")
}

func init() { proto.RegisterFile("mirage/core/v1/genesis.proto", fileDescriptor_192e6edd9e5d5f9b) }

var fileDescriptor_192e6edd9e5d5f9b = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x6d, 0x9a, 0xb6, 0x6b, 0xdc, 0x76, 0x74, 0xde, 0x34, 0x99, 0x6d, 0x84, 0xa8, 0x08, 0x29,
	0x42, 0x5a, 0xa3, 0x6d, 0x12, 0x12, 0x47, 0x36, 0x01, 0xda, 0xb8, 0x54, 0x41, 0x70, 0xe0, 0x12,
	0xb9, 0xed, 0xd7, 0x62, 0x96, 0xc6, 0x91, 0x9d, 0xa6, 0xeb, 0xbf, 0xe0, 0xc8, 0x4f, 0xe0, 0xc8,
	0xcf, 0xd8, 0x81, 0xc3, 0x8e, 0x9c, 0x10, 0xda, 0x0e, 0xfc, 0x07, 0x4e, 0xc8, 0x76, 0xd6, 0xb5,
	0xe3, 0x12, 0xf9, 0x7b, 0xef, 0xe5, 0xb3, 0xfd, 0x9e, 0x3f, 0xb4, 0x37, 0x61, 0x82, 0x8e, 0x21,
	0x18, 0x70, 0x01, 0x41, 0x7e, 0x10, 0x8c, 0x21, 0x01, 0xc9, 0x64, 0x37, 0x15, 0x3c, 0xe3, 0x78,
	0xdd, 0xb0, 0x5d, 0xc5, 0x76, 0xf3, 0x83, 0x9d, 0x0d, 0x3a, 0x61, 0x09, 0x0f, 0xf4, 0xd7, 0x48,
	0x76, 0xb6, 0xc6, 0x7c, 0xcc, 0xf5, 0x32, 0x50, 0xab, 0x02, 0xdd, 0xbd, 0xd7, 0x36, 0xa5, 0x82,
	0x4e, 0x8a, 0xae, 0x9d, 0xbf, 0x65, 0xd4, 0xe8, 0x09, 0x3e, 0x62, 0x31, 0x9c, 0x70, 0x01, 0x78,
	0x0b, 0x55, 0xf9, 0x2c, 0x01, 0x41, 0x2c, 0xcf, 0xf2, 0x9d, 0xd0, 0x14, 0x78, 0x07, 0xd5, 0xa7,
	0x12, 0x44, 0x42, 0x27, 0x40, 0xca, 0x9a, 0x58, 0xd4, 0xea, 0x8f, 0x18, 0x72, 0x88, 0x89, 0xed,
	0x59, 0x7e, 0x35, 0x34, 0x05, 0x7e, 0x84, 0xd0, 0x40, 0x00, 0xcd, 0x60, 0x18, 0xd1, 0x8c, 0x54,
	0x3c, 0xcb, 0xb7, 0x43, 0xa7, 0x40, 0x5e, 0x66, 0x38, 0x40, 0x9b, 0x72, 0xda, 0x97, 0x03, 0xc1,
	0xd2, 0x8c, 0xf1, 0x24, 0x82, 0x8b, 0x94, 0x89, 0x39, 0xa9, 0x6a, 0x1d, 0x5e, 0xa6, 0x5e, 0x69,
	0x46, 0xf5, 0xa3, 0xd3, 0x8c, 0x47, 0x02, 0x12, 0x98, 0x91, 0x9a, 0x67, 0xf9, 0xf5, 0xd0, 0x51,
	0x48, 0xa8, 0x00, 0xfc, 0x04, 0xb5, 0x04, 0x48, 0x10, 0x39, 0x44, 0xa3, 0x69, 0x32, 0x94, 0x64,
	0xcd, 0xb3, 0xfc, 0x4a, 0xd8, 0x2c, 0xc0, 0xd7, 0x0a, 0xc3, 0x7b, 0xc8, 0xe9, 0x33, 0x3e, 0x16,
	0x34, 0xfd, 0x34, 0x27, 0x8e, 0xbe, 0xc6, 0x1d, 0x80, 0xb7, 0x51, 0x8d, 0xe6, 0x34, 0xa3, 0x82,
	0x20, 0x4d, 0x15, 0x95, 0xc2, 0xfb, 0x34, 0x51, 0x96, 0x34, 0x0c, 0x6e, 0x2a, 0x75, 0xef, 0x51,
	0x4c, 0x99, 0x20, 0x4d, 0xe3, 0x94, 0x2e, 0xf0, 0x53, 0xb4, 0x0e, 0xa3, 0x11, 0x0c, 0x32, 0x96,
	0x43, 0x94, 0x52, 0x36, 0x24, 0x2d, 0x7d, 0xd6, 0xd6, 0x02, 0xed, 0x51, 0x36, 0x3c, 0xab, 0xd4,
	0xeb, 0x6d, 0xa7, 0xf3, 0xb5, 0x8c, 0xd6, 0x4f, 0x13, 0x96, 0x31, 0x1a, 0x17, 0x19, 0xe0, 0x00,
	0x55, 0x54, 0x4e, 0xda, 0xfe, 0xc6, 0xe1, 0x6e, 0x77, 0x35, 0xf4, 0xee, 0x52, 0x54, 0xa1, 0x16,
	0xaa, 0x0d, 0x47, 0x3c, 0x8e, 0xf9, 0x0c, 0x86, 0x91, 0xca, 0x44, 0x12, 0xdb, 0xb3, 0x7d, 0x27,
	0x6c, 0xdd, 0xa2, 0xef, 0x15, 0x88, 0xf7, 0x11, 0xfe, 0xcc, 0x59, 0x02, 0xc3, 0x68, 0xc0, 0x27,
	0x93, 0xa9, 0xda, 0x14, 0x24, 0xa9, 0x68, 0xe9, 0x86, 0x61, 0x4e, 0xee, 0x08, 0xe5, 0x67, 0x3f,
	0xe6, 0x83, 0xf3, 0x45, 0xd3, 0xaa, 0x56, 0x36, 0x0b, 0xd0, 0xf4, 0x5c, 0x12, 0xa5, 0x5c, 0x66,
	0x92, 0xd4, 0x56, 0x44, 0x3d, 0x85, 0xa9, 0xa4, 0x6f, 0x45, 0xcb, 0x3b, 0xaf, 0x69, 0x29, 0x2e,
	0xa8, 0xa5, 0xad, 0xcf, 0x2a, 0xf5, 0x72, 0xdb, 0xee, 0x1c, 0x21, 0x27, 0xa4, 0xb3, 0xb7, 0x1f,
	0x7a, 0xca, 0xd4, 0x36, 0xb2, 0xcf, 0x61, 0x5e, 0x3c, 0x49, 0xb5, 0x54, 0xe6, 0xe7, 0x34, 0x9e,
	0xde, 0xbe, 0x46, 0x53, 0x74, 0x7e, 0x58, 0xa8, 0xf9, 0xc6, 0x0c, 0xcd, 0xbb, 0x8c, 0x66, 0x80,
	0x5f, 0xa0, 0x9a, 0x79, 0xed, 0x85, 0x9f, 0xdb, 0xff, 0xf9, 0xa9, 0xd9, 0x63, 0xe7, 0xf2, 0xd7,
	0xe3, 0xd2, 0xb7, 0x3f, 0xdf, 0x9f, 0x59, 0x61, 0xf1, 0x03, 0x3e, 0x45, 0x6d, 0x66, 0xa2, 0x89,
	0x52, 0x63, 0xba, 0x24, 0x65, 0xcf, 0xf6, 0x1b, 0x87, 0xee, 0xfd, 0x26, 0xab, 0x11, 0x86, 0x0f,
	0xd8, 0x4a, 0x2d, 0xf1, 0x73, 0xe4, 0x08, 0x3a, 0x8b, 0xa4, 0x3a, 0x92, 0x4e, 0xa7, 0x71, 0xf8,
	0xf0, 0x7e, 0x8f, 0xc5, 0x65, 0xc3, 0xba, 0xa0, 0x33, 0x7d, 0xfa, 0xe3, 0xfd, 0xcb, 0x6b, 0xd7,
	0xba, 0xba, 0x76, 0xad, 0xdf, 0xd7, 0xae, 0xf5, 0xe5, 0xc6, 0x2d, 0x5d, 0xdd, 0xb8, 0xa5, 0x9f,
	0x37, 0x6e, 0xe9, 0xe3, 0x66, 0x31, 0xd2, 0x17, 0x66, 0xa8, 0xb3, 0x79, 0x0a, 0xb2, 0x5f, 0xd3,
	0x13, 0x7d, 0xf4, 0x6f, 0x00, 0x6e, 0xe6, 0xef, 0x9b, 0x47, 0x04, 0x00, 0x00,
}

func (m *ProfileCore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProfileCore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileCore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EffectivePaid {
		i--
		if m.EffectivePaid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if len(m.Flair) > 0 {
		i -= len(m.Flair)
		copy(dAtA[i:], m.Flair)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Flair)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Banner) > 0 {
		i -= len(m.Banner)
		copy(dAtA[i:], m.Banner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Banner)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Avatar) > 0 {
		i -= len(m.Avatar)
		copy(dAtA[i:], m.Avatar)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Avatar)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Biography) > 0 {
		i -= len(m.Biography)
		copy(dAtA[i:], m.Biography)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Biography)))
		i--
		dAtA[i] = 0x4a
	}
	if m.ReserveFunds != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ReserveFunds))
		i--
		dAtA[i] = 0x38
	}
	if m.AutoRenew {
		i--
		if m.AutoRenew {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.SubscriptionExpiry != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SubscriptionExpiry))
		i--
		dAtA[i] = 0x28
	}
	if m.CreatedAt != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	if m.Level != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Level))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InitialProfile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InitialProfile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InitialProfile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BlockedCommunities) > 0 {
		for iNdEx := len(m.BlockedCommunities) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BlockedCommunities[iNdEx])
			copy(dAtA[i:], m.BlockedCommunities[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.BlockedCommunities[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.BlockedPosts) > 0 {
		for iNdEx := len(m.BlockedPosts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BlockedPosts[iNdEx])
			copy(dAtA[i:], m.BlockedPosts[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.BlockedPosts[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.BlockedUsers) > 0 {
		for iNdEx := len(m.BlockedUsers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BlockedUsers[iNdEx])
			copy(dAtA[i:], m.BlockedUsers[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.BlockedUsers[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.JoinedCommunities) > 0 {
		for iNdEx := len(m.JoinedCommunities) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.JoinedCommunities[iNdEx])
			copy(dAtA[i:], m.JoinedCommunities[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.JoinedCommunities[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.FollowedUsers) > 0 {
		for iNdEx := len(m.FollowedUsers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FollowedUsers[iNdEx])
			copy(dAtA[i:], m.FollowedUsers[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.FollowedUsers[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Core != nil {
		{
			size, err := m.Core.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RawKVPair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RawKVPair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RawKVPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RawState) > 0 {
		for iNdEx := len(m.RawState) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RawState[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.InitialProfiles) > 0 {
		for iNdEx := len(m.InitialProfiles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InitialProfiles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProfileCore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Level != 0 {
		n += 1 + sovGenesis(uint64(m.Level))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovGenesis(uint64(m.CreatedAt))
	}
	if m.SubscriptionExpiry != 0 {
		n += 1 + sovGenesis(uint64(m.SubscriptionExpiry))
	}
	if m.AutoRenew {
		n += 2
	}
	if m.ReserveFunds != 0 {
		n += 1 + sovGenesis(uint64(m.ReserveFunds))
	}
	l = len(m.Biography)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Banner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Flair)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.EffectivePaid {
		n += 2
	}
	return n
}

func (m *InitialProfile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Core != nil {
		l = m.Core.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.FollowedUsers) > 0 {
		for _, s := range m.FollowedUsers {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.JoinedCommunities) > 0 {
		for _, s := range m.JoinedCommunities {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BlockedUsers) > 0 {
		for _, s := range m.BlockedUsers {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BlockedPosts) > 0 {
		for _, s := range m.BlockedPosts {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BlockedCommunities) > 0 {
		for _, s := range m.BlockedCommunities {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *RawKVPair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.InitialProfiles) > 0 {
		for _, e := range m.InitialProfiles {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RawState) > 0 {
		for _, e := range m.RawState {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProfileCore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProfileCore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProfileCore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			m.Level = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionExpiry", wireType)
			}
			m.SubscriptionExpiry = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionExpiry |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoRenew", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AutoRenew = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveFunds", wireType)
			}
			m.ReserveFunds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReserveFunds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Biography", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Biography = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Banner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Banner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flair", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Flair = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectivePaid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EffectivePaid = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InitialProfile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InitialProfile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InitialProfile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Core", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Core == nil {
				m.Core = &ProfileCore{}
			}
			if err := m.Core.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FollowedUsers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FollowedUsers = append(m.FollowedUsers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinedCommunities", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JoinedCommunities = append(m.JoinedCommunities, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockedUsers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockedUsers = append(m.BlockedUsers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockedPosts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockedPosts = append(m.BlockedPosts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockedCommunities", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockedCommunities = append(m.BlockedCommunities, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RawKVPair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RawKVPair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RawKVPair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialProfiles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialProfiles = append(m.InitialProfiles, &InitialProfile{})
			if err := m.InitialProfiles[len(m.InitialProfiles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawState = append(m.RawState, &RawKVPair{})
			if err := m.RawState[len(m.RawState)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
