// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mirage/core/v1/params.proto

package types

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TierConfig defines the configuration for a membership tier.
type TierConfig struct {
	// uint64 fields
	PeriodFee         uint64 `protobuf:"varint,1,opt,name=period_fee,json=periodFee,proto3" json:"period_fee,omitempty"`
	MaxEnabledAgents  uint64 `protobuf:"varint,2,opt,name=max_enabled_agents,json=maxEnabledAgents,proto3" json:"max_enabled_agents,omitempty"`
	MaxFollowedUsers  uint64 `protobuf:"varint,3,opt,name=max_followed_users,json=maxFollowedUsers,proto3" json:"max_followed_users,omitempty"`
	MaxFollowedTopics uint64 `protobuf:"varint,4,opt,name=max_followed_topics,json=maxFollowedTopics,proto3" json:"max_followed_topics,omitempty"`
	MaxBlockedUsers   uint64 `protobuf:"varint,5,opt,name=max_blocked_users,json=maxBlockedUsers,proto3" json:"max_blocked_users,omitempty"`
	MaxBlockedPosts   uint64 `protobuf:"varint,6,opt,name=max_blocked_posts,json=maxBlockedPosts,proto3" json:"max_blocked_posts,omitempty"`
	MaxBlockedTopics  uint64 `protobuf:"varint,7,opt,name=max_blocked_topics,json=maxBlockedTopics,proto3" json:"max_blocked_topics,omitempty"`
	MaxTitleLength    uint64 `protobuf:"varint,8,opt,name=max_title_length,json=maxTitleLength,proto3" json:"max_title_length,omitempty"`
	MaxContentLength  uint64 `protobuf:"varint,9,opt,name=max_content_length,json=maxContentLength,proto3" json:"max_content_length,omitempty"`
	EditingTimeMins   uint64 `protobuf:"varint,10,opt,name=editing_time_mins,json=editingTimeMins,proto3" json:"editing_time_mins,omitempty"`
	// double fields
	VoteWeight float64 `protobuf:"fixed64,13,opt,name=vote_weight,json=voteWeight,proto3" json:"vote_weight,omitempty"`
	// bool fields
	CanBeAgent       bool `protobuf:"varint,15,opt,name=can_be_agent,json=canBeAgent,proto3" json:"can_be_agent,omitempty"`
	CanRemoveAnon    bool `protobuf:"varint,16,opt,name=can_remove_anon,json=canRemoveAnon,proto3" json:"can_remove_anon,omitempty"`
	CanHaveBiography bool `protobuf:"varint,17,opt,name=can_have_biography,json=canHaveBiography,proto3" json:"can_have_biography,omitempty"`
	CanHaveAvatar    bool `protobuf:"varint,18,opt,name=can_have_avatar,json=canHaveAvatar,proto3" json:"can_have_avatar,omitempty"`
	CanHaveBanner    bool `protobuf:"varint,19,opt,name=can_have_banner,json=canHaveBanner,proto3" json:"can_have_banner,omitempty"`
	CanHaveFlair     bool `protobuf:"varint,20,opt,name=can_have_flair,json=canHaveFlair,proto3" json:"can_have_flair,omitempty"`
	// max_biography_length is the max biography length for this tier (0 = disabled)
	MaxBiographyLength uint64 `protobuf:"varint,21,opt,name=max_biography_length,json=maxBiographyLength,proto3" json:"max_biography_length,omitempty"`
}

func (m *TierConfig) Reset()         { *m = TierConfig{} }
func (m *TierConfig) String() string { return proto.CompactTextString(m) }
func (*TierConfig) ProtoMessage()    {}
func (*TierConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c539f4235465551a, []int{0}
}
func (m *TierConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TierConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TierConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TierConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TierConfig.Merge(m, src)
}
func (m *TierConfig) XXX_Size() int {
	return m.Size()
}
func (m *TierConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TierConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TierConfig proto.InternalMessageInfo

func (m *TierConfig) GetPeriodFee() uint64 {
	if m != nil {
		return m.PeriodFee
	}
	return 0
}

func (m *TierConfig) GetMaxEnabledAgents() uint64 {
	if m != nil {
		return m.MaxEnabledAgents
	}
	return 0
}

func (m *TierConfig) GetMaxFollowedUsers() uint64 {
	if m != nil {
		return m.MaxFollowedUsers
	}
	return 0
}

func (m *TierConfig) GetMaxFollowedTopics() uint64 {
	if m != nil {
		return m.MaxFollowedTopics
	}
	return 0
}

func (m *TierConfig) GetMaxBlockedUsers() uint64 {
	if m != nil {
		return m.MaxBlockedUsers
	}
	return 0
}

func (m *TierConfig) GetMaxBlockedPosts() uint64 {
	if m != nil {
		return m.MaxBlockedPosts
	}
	return 0
}

func (m *TierConfig) GetMaxBlockedTopics() uint64 {
	if m != nil {
		return m.MaxBlockedTopics
	}
	return 0
}

func (m *TierConfig) GetMaxTitleLength() uint64 {
	if m != nil {
		return m.MaxTitleLength
	}
	return 0
}

func (m *TierConfig) GetMaxContentLength() uint64 {
	if m != nil {
		return m.MaxContentLength
	}
	return 0
}

func (m *TierConfig) GetEditingTimeMins() uint64 {
	if m != nil {
		return m.EditingTimeMins
	}
	return 0
}

func (m *TierConfig) GetVoteWeight() float64 {
	if m != nil {
		return m.VoteWeight
	}
	return 0
}

func (m *TierConfig) GetCanBeAgent() bool {
	if m != nil {
		return m.CanBeAgent
	}
	return false
}

func (m *TierConfig) GetCanRemoveAnon() bool {
	if m != nil {
		return m.CanRemoveAnon
	}
	return false
}

func (m *TierConfig) GetCanHaveBiography() bool {
	if m != nil {
		return m.CanHaveBiography
	}
	return false
}

func (m *TierConfig) GetCanHaveAvatar() bool {
	if m != nil {
		return m.CanHaveAvatar
	}
	return false
}

func (m *TierConfig) GetCanHaveBanner() bool {
	if m != nil {
		return m.CanHaveBanner
	}
	return false
}

func (m *TierConfig) GetCanHaveFlair() bool {
	if m != nil {
		return m.CanHaveFlair
	}
	return false
}

func (m *TierConfig) GetMaxBiographyLength() uint64 {
	if m != nil {
		return m.MaxBiographyLength
	}
	return 0
}

// Params defines the parameters for the module.
type Params struct {
	// min_difficulty defines the base PoW target: base_target = 2^(256 - min_difficulty).
	// The dynamic difficulty is stored on-chain as integer steps (0 = base).
	MinDifficulty uint64 `protobuf:"varint,1,opt,name=min_difficulty,json=minDifficulty,proto3" json:"min_difficulty,omitempty"`
	// pow_message_window is the sliding window size (in blocks) over which PoW message volume is measured
	PowMessageWindow uint64 `protobuf:"varint,2,opt,name=pow_message_window,json=powMessageWindow,proto3" json:"pow_message_window,omitempty"`
	// pow_message_limit: if >= this many PoW messages observed in the window, increase difficulty
	PowMessageLimit uint64 `protobuf:"varint,3,opt,name=pow_message_limit,json=powMessageLimit,proto3" json:"pow_message_limit,omitempty"`
	// pow_calm_period_definition: if < this many PoW messages observed in the window, it's a calm period
	PowCalmPeriodDefinition uint64 `protobuf:"varint,4,opt,name=pow_calm_period_definition,json=powCalmPeriodDefinition,proto3" json:"pow_calm_period_definition,omitempty"`
	// pow_calm_sequence_threshold: number of consecutive calm periods before decreasing difficulty
	PowCalmSequenceThreshold uint64 `protobuf:"varint,5,opt,name=pow_calm_sequence_threshold,json=powCalmSequenceThreshold,proto3" json:"pow_calm_sequence_threshold,omitempty"`
	// mint_interval is the number of blocks between minting events
	MintInterval uint64 `protobuf:"varint,7,opt,name=mint_interval,json=mintInterval,proto3" json:"mint_interval,omitempty"`
	// mint_quantity is the number of umirage minted per mint event
	MintQuantity uint64 `protobuf:"varint,8,opt,name=mint_quantity,json=mintQuantity,proto3" json:"mint_quantity,omitempty"`
	// block_hash_window is the number of recent committed block hashes to accept for PoW validation
	BlockHashWindow uint64 `protobuf:"varint,9,opt,name=block_hash_window,json=blockHashWindow,proto3" json:"block_hash_window,omitempty"`
	// pow_difficulty_allowance: number of blocks after a change where previous difficulty is accepted
	PowDifficultyAllowance uint64 `protobuf:"varint,10,opt,name=pow_difficulty_allowance,json=powDifficultyAllowance,proto3" json:"pow_difficulty_allowance,omitempty"`
	// max_username_size is the maximum username length
	MaxUsernameSize uint64 `protobuf:"varint,34,opt,name=max_username_size,json=maxUsernameSize,proto3" json:"max_username_size,omitempty"`
	// max_topic_size is the maximum topic length
	MaxTopicSize uint64 `protobuf:"varint,35,opt,name=max_topic_size,json=maxTopicSize,proto3" json:"max_topic_size,omitempty"`
	// min_username_size is the minimum username length
	MinUsernameSize uint64 `protobuf:"varint,36,opt,name=min_username_size,json=minUsernameSize,proto3" json:"min_username_size,omitempty"`
	// min_topic_size is the minimum topic length
	MinTopicSize uint64 `protobuf:"varint,37,opt,name=min_topic_size,json=minTopicSize,proto3" json:"min_topic_size,omitempty"`
	// mint_dynamic_credit_cap caps per-interval relay credits per validator
	MintDynamicCreditCap uint64 `protobuf:"varint,38,opt,name=mint_dynamic_credit_cap,json=mintDynamicCreditCap,proto3" json:"mint_dynamic_credit_cap,omitempty"`
	// mint_dynamic_split is fraction [0,1] of MintQuantity allocated to dynamic pool
	MintDynamicSplit float64 `protobuf:"fixed64,39,opt,name=mint_dynamic_split,json=mintDynamicSplit,proto3" json:"mint_dynamic_split,omitempty"`
	// subscription_period is the renewal period in minutes; 0 = one-time payment, 43200 = 30 days
	SubscriptionPeriod uint64 `protobuf:"varint,40,opt,name=subscription_period,json=subscriptionPeriod,proto3" json:"subscription_period,omitempty"`
	// tiers defines the tier configurations, indexed by user-level-to-tier mapping.
	// The exact level -> tier-index mapping is defined by LevelToTierIndex in
	// x/core/types/params.go: level 0 (Free) -> 0, level 1 (Subscriber) -> 1,
	// level 10 (Agent) -> 2, level >= 100 (Admin) -> 2 (inherits Agent tier).
	// Levels 2-9 are reserved for future subscription tiers and currently invalid.
	Tiers []*TierConfig `protobuf:"bytes,41,rep,name=tiers,proto3" json:"tiers,omitempty"`
	// subscription_reserve_percent is the fraction of period fee escrowed as gas reserve [0.0, 1.0]
	// Default: 0.80 (80% of period fee goes to reserve, 20% burned)
	SubscriptionReservePercent float64 `protobuf:"fixed64,42,opt,name=subscription_reserve_percent,json=subscriptionReservePercent,proto3" json:"subscription_reserve_percent,omitempty"`
	// relay_min_gas_price is the minimum gas price for relay fee calculation (in umirage per gas unit)
	// Default: 5000 (5000 umirage per gas). Set to match node's minimum-gas-prices.
	RelayMinGasPrice uint64 `protobuf:"varint,43,opt,name=relay_min_gas_price,json=relayMinGasPrice,proto3" json:"relay_min_gas_price,omitempty"`
	// relay_max_gas_fee is the maximum gas fee that can be deducted per relayed transaction (in umirage)
	// Default: 500,000,000 (500 MIRAGE). Protects users from unexpectedly high fees.
	RelayMaxGasFee uint64 `protobuf:"varint,44,opt,name=relay_max_gas_fee,json=relayMaxGasFee,proto3" json:"relay_max_gas_fee,omitempty"`
	// max_envelope_age is the maximum age in seconds for envelope_timestamp.
	// Transactions with envelope_timestamp older than (now - max_envelope_age) are rejected.
	// This provides replay protection by ensuring stale transactions cannot be resubmitted.
	// Default: 60 (reject transactions older than 60 seconds).
	MaxEnvelopeAge uint64 `protobuf:"varint,45,opt,name=max_envelope_age,json=maxEnvelopeAge,proto3" json:"max_envelope_age,omitempty"`
	// pow_difficulty_step is the fractional step for the exponential difficulty factor [0.01, 1.0]
	// Effective factor: 1000 * (1 + step)^difficulty. On busy: difficulty += 1. On calm: difficulty -= 1.
	// Default: 0.25 (25% per step)
	PowDifficultyStep float64 `protobuf:"fixed64,52,opt,name=pow_difficulty_step,json=powDifficultyStep,proto3" json:"pow_difficulty_step,omitempty"`
	// award_configs defines available award types and their costs in umirage
	AwardConfigs []*AwardConfig `protobuf:"bytes,53,rep,name=award_configs,json=awardConfigs,proto3" json:"award_configs,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c539f4235465551a, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinDifficulty() uint64 {
	if m != nil {
		return m.MinDifficulty
	}
	return 0
}

func (m *Params) GetPowMessageWindow() uint64 {
	if m != nil {
		return m.PowMessageWindow
	}
	return 0
}

func (m *Params) GetPowMessageLimit() uint64 {
	if m != nil {
		return m.PowMessageLimit
	}
	return 0
}

func (m *Params) GetPowCalmPeriodDefinition() uint64 {
	if m != nil {
		return m.PowCalmPeriodDefinition
	}
	return 0
}

func (m *Params) GetPowCalmSequenceThreshold() uint64 {
	if m != nil {
		return m.PowCalmSequenceThreshold
	}
	return 0
}

func (m *Params) GetMintInterval() uint64 {
	if m != nil {
		return m.MintInterval
	}
	return 0
}

func (m *Params) GetMintQuantity() uint64 {
	if m != nil {
		return m.MintQuantity
	}
	return 0
}

func (m *Params) GetBlockHashWindow() uint64 {
	if m != nil {
		return m.BlockHashWindow
	}
	return 0
}

func (m *Params) GetPowDifficultyAllowance() uint64 {
	if m != nil {
		return m.PowDifficultyAllowance
	}
	return 0
}

func (m *Params) GetMaxUsernameSize() uint64 {
	if m != nil {
		return m.MaxUsernameSize
	}
	return 0
}

func (m *Params) GetMaxTopicSize() uint64 {
	if m != nil {
		return m.MaxTopicSize
	}
	return 0
}

func (m *Params) GetMinUsernameSize() uint64 {
	if m != nil {
		return m.MinUsernameSize
	}
	return 0
}

func (m *Params) GetMinTopicSize() uint64 {
	if m != nil {
		return m.MinTopicSize
	}
	return 0
}

func (m *Params) GetMintDynamicCreditCap() uint64 {
	if m != nil {
		return m.MintDynamicCreditCap
	}
	return 0
}

func (m *Params) GetMintDynamicSplit() float64 {
	if m != nil {
		return m.MintDynamicSplit
	}
	return 0
}

func (m *Params) GetSubscriptionPeriod() uint64 {
	if m != nil {
		return m.SubscriptionPeriod
	}
	return 0
}

func (m *Params) GetTiers() []*TierConfig {
	if m != nil {
		return m.Tiers
	}
	return nil
}

func (m *Params) GetSubscriptionReservePercent() float64 {
	if m != nil {
		return m.SubscriptionReservePercent
	}
	return 0
}

func (m *Params) GetRelayMinGasPrice() uint64 {
	if m != nil {
		return m.RelayMinGasPrice
	}
	return 0
}

func (m *Params) GetRelayMaxGasFee() uint64 {
	if m != nil {
		return m.RelayMaxGasFee
	}
	return 0
}

func (m *Params) GetMaxEnvelopeAge() uint64 {
	if m != nil {
		return m.MaxEnvelopeAge
	}
	return 0
}

func (m *Params) GetPowDifficultyStep() float64 {
	if m != nil {
		return m.PowDifficultyStep
	}
	return 0
}

func (m *Params) GetAwardConfigs() []*AwardConfig {
	if m != nil {
		return m.AwardConfigs
	}
	return nil
}

// AwardConfig defines a single award type and its cost.
type AwardConfig struct {
	// name is the unique identifier for this award type (e.g., "quality_post")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// cost is the amount of umirage burned when giving this award (0 for free awards)
	Cost uint64 `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (m *AwardConfig) Reset()         { *m = AwardConfig{} }
func (m *AwardConfig) String() string { return proto.CompactTextString(m) }
func (*AwardConfig) ProtoMessage()    {}
func (*AwardConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c539f4235465551a, []int{2}
}
func (m *AwardConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AwardConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AwardConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AwardConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AwardConfig.Merge(m, src)
}
func (m *AwardConfig) XXX_Size() int {
	return m.Size()
}
func (m *AwardConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AwardConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AwardConfig proto.InternalMessageInfo

func (m *AwardConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AwardConfig) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func init() {
	proto.RegisterType((*TierConfig)(nil), "mirage.core.v1.TierConfig")
	proto.RegisterType((*Params)(nil), "mirage.core.v1.Params")
	proto.RegisterType((*AwardConfig)(nil), "mirage.core.v1.AwardConfig")
}

func init() { proto.RegisterFile("mirage/core/v1/params.proto", fileDescriptor_c539f4235465551a) }

var fileDescriptor_c539f4235465551a = []byte{
	// 1114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x96, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0xc7, 0xa3, 0x46, 0x71, 0x65, 0x5a, 0xb6, 0x25, 0xda, 0x6d, 0x16, 0x4e, 0xa3, 0x18, 0xce,
	0x47, 0x15, 0x37, 0x91, 0xf2, 0x09, 0x14, 0x09, 0x0a, 0x44, 0x76, 0xe2, 0xa4, 0x46, 0x0c, 0xb8,
	0xb2, 0x83, 0x00, 0xbd, 0x10, 0xa3, 0xd5, 0x68, 0x45, 0x74, 0x97, 0xdc, 0x2c, 0x69, 0x7d, 0xe4,
	0x11, 0x72, 0xea, 0xa1, 0x0f, 0xd0, 0x47, 0xe8, 0x63, 0xf4, 0x98, 0x63, 0x8f, 0x85, 0x7d, 0x68,
	0x1f, 0xa3, 0xe0, 0xc7, 0xae, 0x25, 0xf7, 0x62, 0xac, 0xff, 0xf3, 0xe3, 0xec, 0xec, 0x90, 0xff,
	0xa1, 0xc8, 0xb5, 0x84, 0x67, 0x10, 0x61, 0x3b, 0x94, 0x19, 0xb6, 0x47, 0x0f, 0xdb, 0x29, 0x64,
	0x90, 0xa8, 0x56, 0x9a, 0x49, 0x2d, 0xe9, 0x8a, 0x0b, 0xb6, 0x4c, 0xb0, 0x35, 0x7a, 0xb8, 0x51,
	0x87, 0x84, 0x0b, 0xd9, 0xb6, 0x7f, 0x1d, 0xb2, 0xb1, 0x1e, 0xc9, 0x48, 0xda, 0xc7, 0xb6, 0x79,
	0x72, 0xea, 0xd6, 0x6f, 0x0b, 0x84, 0x1c, 0x73, 0xcc, 0x76, 0xa5, 0x18, 0xf0, 0x88, 0x5e, 0x27,
	0x24, 0xc5, 0x8c, 0xcb, 0x3e, 0x1b, 0x20, 0x06, 0xa5, 0xcd, 0x52, 0xb3, 0xdc, 0x5d, 0x74, 0xca,
	0x1e, 0x22, 0xbd, 0x47, 0x68, 0x02, 0x13, 0x86, 0x02, 0x7a, 0x31, 0xf6, 0x19, 0x44, 0x28, 0xb4,
	0x0a, 0xbe, 0xb0, 0x58, 0x2d, 0x81, 0xc9, 0x2b, 0x17, 0xe8, 0x58, 0x3d, 0xa7, 0x07, 0x32, 0x8e,
	0xe5, 0x18, 0xfb, 0xec, 0x44, 0x61, 0xa6, 0x82, 0xcb, 0x05, 0xbd, 0xe7, 0x03, 0xef, 0x8c, 0x4e,
	0x5b, 0x64, 0x6d, 0x8e, 0xd6, 0x32, 0xe5, 0xa1, 0x0a, 0xca, 0x16, 0xaf, 0xcf, 0xe0, 0xc7, 0x36,
	0x40, 0xb7, 0x89, 0x11, 0x59, 0x2f, 0x96, 0xe1, 0x2f, 0x45, 0xf2, 0x2b, 0x96, 0x5e, 0x4d, 0x60,
	0xb2, 0xe3, 0x74, 0x97, 0xfb, 0x02, 0x9b, 0x4a, 0xa5, 0x55, 0xb0, 0x70, 0x91, 0x3d, 0x34, 0x72,
	0x5e, 0x75, 0xce, 0xfa, 0x32, 0xbe, 0x2c, 0xaa, 0xf6, 0xb0, 0xaf, 0xa2, 0x49, 0x8c, 0xc6, 0x34,
	0xd7, 0x31, 0xb2, 0x18, 0x45, 0xa4, 0x87, 0x41, 0xc5, 0xb2, 0x2b, 0x09, 0x4c, 0x8e, 0x8d, 0xfc,
	0xd6, 0xaa, 0x79, 0xde, 0x50, 0x0a, 0x8d, 0x42, 0xe7, 0xec, 0x62, 0x91, 0x77, 0xd7, 0x05, 0x3c,
	0xbd, 0x4d, 0xea, 0xd8, 0xe7, 0x9a, 0x8b, 0x88, 0x69, 0x9e, 0x20, 0x4b, 0xb8, 0x50, 0x01, 0x71,
	0x15, 0xfb, 0xc0, 0x31, 0x4f, 0xf0, 0x80, 0x0b, 0x45, 0x6f, 0x90, 0xa5, 0x91, 0xd4, 0xc8, 0xc6,
	0xc8, 0xa3, 0xa1, 0x0e, 0x96, 0x37, 0x4b, 0xcd, 0x52, 0x97, 0x18, 0xe9, 0xbd, 0x55, 0xe8, 0x26,
	0xa9, 0x86, 0x20, 0x58, 0x0f, 0xdd, 0x8e, 0x05, 0xab, 0x9b, 0xa5, 0x66, 0xa5, 0x4b, 0x42, 0x10,
	0x3b, 0x68, 0xf7, 0x8a, 0xde, 0x21, 0xab, 0x86, 0xc8, 0x30, 0x91, 0x23, 0x64, 0x20, 0xa4, 0x08,
	0x6a, 0x16, 0x5a, 0x0e, 0x41, 0x74, 0xad, 0xda, 0x11, 0x52, 0x98, 0x8f, 0x30, 0xdc, 0x10, 0x46,
	0xc8, 0x7a, 0x5c, 0x46, 0x19, 0xa4, 0xc3, 0x69, 0x50, 0xb7, 0x68, 0x2d, 0x04, 0xf1, 0x06, 0x46,
	0xb8, 0x93, 0xeb, 0x79, 0x56, 0x4b, 0xc3, 0x08, 0x34, 0x64, 0x01, 0x2d, 0xb2, 0x1a, 0xb4, 0x63,
	0xc5, 0x39, 0xae, 0x07, 0x42, 0x60, 0x16, 0xac, 0xcd, 0x71, 0x3b, 0x56, 0xa4, 0xb7, 0xc8, 0x4a,
	0xc1, 0x0d, 0x62, 0xe0, 0x59, 0xb0, 0x6e, 0xb1, 0xaa, 0xc7, 0xf6, 0x8c, 0x46, 0x1f, 0x90, 0x75,
	0xbb, 0x81, 0x79, 0x19, 0x79, 0xab, 0xbf, 0xb2, 0xdd, 0x33, 0x9b, 0x50, 0x54, 0xe8, 0x9a, 0xfd,
	0xac, 0xfc, 0xef, 0xef, 0x37, 0x4a, 0xfb, 0xe5, 0xca, 0x52, 0xad, 0xba, 0x5f, 0xae, 0x54, 0x6b,
	0xcb, 0x5b, 0x9f, 0x16, 0xc9, 0xc2, 0xa1, 0x35, 0x18, 0xbd, 0x4d, 0x56, 0x12, 0x2e, 0x58, 0x9f,
	0x0f, 0x06, 0x3c, 0x3c, 0x89, 0xf5, 0xd4, 0xdb, 0x62, 0x39, 0xe1, 0xe2, 0x65, 0x21, 0x9a, 0xce,
	0xa4, 0x72, 0xcc, 0x12, 0x54, 0x0a, 0x22, 0x64, 0x63, 0x2e, 0xfa, 0x72, 0x9c, 0x5b, 0x23, 0x95,
	0xe3, 0x03, 0x17, 0x78, 0x6f, 0x75, 0xb3, 0xbd, 0xb3, 0x74, 0xcc, 0x13, 0xae, 0xbd, 0x33, 0x56,
	0xcf, 0xe1, 0xb7, 0x46, 0xa6, 0xcf, 0xc9, 0x86, 0x61, 0x43, 0x88, 0x13, 0xe6, 0xcd, 0xd9, 0xc7,
	0x01, 0x17, 0x5c, 0x73, 0x29, 0xbc, 0x3f, 0xae, 0xa6, 0x72, 0xbc, 0x0b, 0x71, 0x72, 0x68, 0xe3,
	0x2f, 0x8b, 0x30, 0xfd, 0x81, 0x5c, 0x2b, 0x16, 0x2b, 0xfc, 0x70, 0x82, 0x22, 0x44, 0xa6, 0x87,
	0x19, 0xaa, 0xa1, 0x8c, 0xfb, 0xde, 0x2f, 0x81, 0x5f, 0x7d, 0xe4, 0x81, 0xe3, 0x3c, 0x4e, 0x6f,
	0x12, 0xf3, 0x99, 0x9a, 0x71, 0xa1, 0x31, 0x1b, 0x41, 0xec, 0x7d, 0x50, 0x35, 0xe2, 0x8f, 0x5e,
	0x2b, 0xa0, 0x0f, 0x27, 0x20, 0x34, 0xd7, 0x53, 0x6f, 0x00, 0x0b, 0xfd, 0xe4, 0x35, 0xf3, 0xc5,
	0xd6, 0x52, 0x6c, 0x08, 0x6a, 0x98, 0xb7, 0xc7, 0x9d, 0xfe, 0x55, 0x1b, 0x78, 0x03, 0x6a, 0xe8,
	0xbb, 0xf3, 0x3d, 0x31, 0x15, 0xcd, 0xb4, 0x9c, 0x81, 0xb1, 0x3e, 0x88, 0x10, 0xbd, 0x07, 0xbe,
	0x4e, 0xe5, 0xf8, 0xbc, 0xf9, 0x9d, 0x3c, 0x9a, 0x1b, 0xdd, 0x0c, 0x03, 0x01, 0x09, 0x32, 0xc5,
	0x3f, 0x62, 0xb0, 0x55, 0x18, 0xfd, 0x9d, 0xd7, 0x8f, 0xf8, 0x47, 0x34, 0xa7, 0xc9, 0x5a, 0xd7,
	0x18, 0xd9, 0x81, 0x37, 0x7d, 0xdd, 0x30, 0xb1, 0xee, 0xb6, 0x94, 0xc9, 0xc8, 0xc5, 0x85, 0x8c,
	0xb7, 0x7c, 0x46, 0x2e, 0xfe, 0x97, 0x91, 0x8b, 0xd9, 0x8c, 0xb7, 0x8b, 0x4e, 0x9c, 0x67, 0x7c,
	0x4a, 0xae, 0xda, 0x76, 0xf5, 0xa7, 0x02, 0x12, 0x1e, 0xb2, 0x30, 0x33, 0x86, 0x66, 0x21, 0xa4,
	0xc1, 0x1d, 0x8b, 0xaf, 0x9b, 0xf0, 0x4b, 0x17, 0xdd, 0xb5, 0xc1, 0x5d, 0x48, 0xed, 0xfc, 0x98,
	0x5d, 0xa6, 0xd2, 0x98, 0xeb, 0xe0, 0x5b, 0x6b, 0xf6, 0xda, 0xcc, 0x8a, 0x23, 0xa3, 0xd3, 0x36,
	0x59, 0x53, 0x27, 0x3d, 0x15, 0x66, 0x3c, 0x35, 0xe7, 0xc0, 0x1f, 0x9c, 0xa0, 0xe9, 0x3c, 0x30,
	0x1b, 0x72, 0x47, 0x86, 0x3e, 0x20, 0x57, 0x34, 0x37, 0x23, 0xf4, 0xee, 0xe6, 0xe5, 0xe6, 0xd2,
	0xa3, 0x8d, 0xd6, 0xfc, 0x8d, 0xd2, 0x3a, 0xbf, 0x24, 0xba, 0x0e, 0xa4, 0x2f, 0xc8, 0x37, 0x73,
	0xaf, 0xc8, 0x50, 0x61, 0x36, 0x42, 0xf3, 0xaa, 0xd0, 0x4c, 0x99, 0x6d, 0x5b, 0xda, 0xc6, 0x2c,
	0xd3, 0x75, 0xc8, 0xa1, 0x23, 0xe8, 0x7d, 0xb2, 0x96, 0x61, 0x0c, 0x53, 0x33, 0xdd, 0x58, 0x04,
	0x8a, 0xa5, 0x19, 0x0f, 0x31, 0xf8, 0xce, 0x99, 0xc6, 0x86, 0x0e, 0xb8, 0x78, 0x0d, 0xea, 0xd0,
	0xe8, 0xf4, 0x2e, 0xa9, 0x7b, 0x1c, 0x26, 0x16, 0x37, 0x77, 0xd4, 0x3d, 0x37, 0x6c, 0x1d, 0x0c,
	0x93, 0xd7, 0xa0, 0xcc, 0x45, 0xe5, 0xc7, 0x32, 0x8a, 0x11, 0xc6, 0x32, 0xb5, 0x73, 0x2f, 0xb8,
	0x5f, 0x8c, 0xe5, 0x57, 0x5e, 0xee, 0x44, 0x68, 0xae, 0x9d, 0x0b, 0x67, 0x4d, 0x69, 0x4c, 0x83,
	0x27, 0xb6, 0xf8, 0xfa, 0xdc, 0x31, 0x3b, 0xd2, 0x98, 0xd2, 0x17, 0x64, 0x19, 0xc6, 0x90, 0xf5,
	0xcd, 0x20, 0x1f, 0xf0, 0x48, 0x05, 0x4f, 0x6d, 0xbf, 0xae, 0x5d, 0xec, 0x57, 0xc7, 0x40, 0xbe,
	0x61, 0x55, 0x38, 0xff, 0x47, 0x3d, 0xbb, 0x6e, 0xa6, 0xcd, 0xa7, 0x7f, 0xfe, 0xd8, 0x5e, 0xf7,
	0x37, 0xfa, 0xc4, 0xdd, 0xe9, 0x6e, 0xde, 0xec, 0x97, 0x2b, 0xad, 0xda, 0xa3, 0xfd, 0x72, 0xe5,
	0x51, 0xed, 0xf1, 0x7e, 0xb9, 0xf2, 0xb8, 0xf6, 0x64, 0xeb, 0x39, 0x59, 0x9a, 0xc9, 0x46, 0x29,
	0x29, 0x9b, 0x13, 0x67, 0xc7, 0xd0, 0x62, 0xd7, 0x3e, 0x1b, 0x2d, 0x94, 0x4a, 0xfb, 0x79, 0x63,
	0x9f, 0xdd, 0x54, 0xdb, 0xb9, 0xff, 0xe7, 0x69, 0xa3, 0xf4, 0xf9, 0xb4, 0x51, 0xfa, 0xfb, 0xb4,
	0x51, 0xfa, 0xf5, 0xac, 0x71, 0xe9, 0xf3, 0x59, 0xe3, 0xd2, 0x5f, 0x67, 0x8d, 0x4b, 0x3f, 0xaf,
	0xcd, 0xbf, 0x5e, 0x4f, 0x53, 0x54, 0xbd, 0x05, 0xfb, 0xb3, 0xe0, 0xf1, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x93, 0xd4, 0x60, 0x3b, 0x6e, 0x08, 0x00, 0x00,
}

func (this *TierConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TierConfig)
	if !ok {
		that2, ok := that.(TierConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PeriodFee != that1.PeriodFee {
		return false
	}
	if this.MaxEnabledAgents != that1.MaxEnabledAgents {
		return false
	}
	if this.MaxFollowedUsers != that1.MaxFollowedUsers {
		return false
	}
	if this.MaxFollowedTopics != that1.MaxFollowedTopics {
		return false
	}
	if this.MaxBlockedUsers != that1.MaxBlockedUsers {
		return false
	}
	if this.MaxBlockedPosts != that1.MaxBlockedPosts {
		return false
	}
	if this.MaxBlockedTopics != that1.MaxBlockedTopics {
		return false
	}
	if this.MaxTitleLength != that1.MaxTitleLength {
		return false
	}
	if this.MaxContentLength != that1.MaxContentLength {
		return false
	}
	if this.EditingTimeMins != that1.EditingTimeMins {
		return false
	}
	if this.VoteWeight != that1.VoteWeight {
		return false
	}
	if this.CanBeAgent != that1.CanBeAgent {
		return false
	}
	if this.CanRemoveAnon != that1.CanRemoveAnon {
		return false
	}
	if this.CanHaveBiography != that1.CanHaveBiography {
		return false
	}
	if this.CanHaveAvatar != that1.CanHaveAvatar {
		return false
	}
	if this.CanHaveBanner != that1.CanHaveBanner {
		return false
	}
	if this.CanHaveFlair != that1.CanHaveFlair {
		return false
	}
	if this.MaxBiographyLength != that1.MaxBiographyLength {
		return false
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MinDifficulty != that1.MinDifficulty {
		return false
	}
	if this.PowMessageWindow != that1.PowMessageWindow {
		return false
	}
	if this.PowMessageLimit != that1.PowMessageLimit {
		return false
	}
	if this.PowCalmPeriodDefinition != that1.PowCalmPeriodDefinition {
		return false
	}
	if this.PowCalmSequenceThreshold != that1.PowCalmSequenceThreshold {
		return false
	}
	if this.MintInterval != that1.MintInterval {
		return false
	}
	if this.MintQuantity != that1.MintQuantity {
		return false
	}
	if this.BlockHashWindow != that1.BlockHashWindow {
		return false
	}
	if this.PowDifficultyAllowance != that1.PowDifficultyAllowance {
		return false
	}
	if this.MaxUsernameSize != that1.MaxUsernameSize {
		return false
	}
	if this.MaxTopicSize != that1.MaxTopicSize {
		return false
	}
	if this.MinUsernameSize != that1.MinUsernameSize {
		return false
	}
	if this.MinTopicSize != that1.MinTopicSize {
		return false
	}
	if this.MintDynamicCreditCap != that1.MintDynamicCreditCap {
		return false
	}
	if this.MintDynamicSplit != that1.MintDynamicSplit {
		return false
	}
	if this.SubscriptionPeriod != that1.SubscriptionPeriod {
		return false
	}
	if len(this.Tiers) != len(that1.Tiers) {
		return false
	}
	for i := range this.Tiers {
		if !this.Tiers[i].Equal(that1.Tiers[i]) {
			return false
		}
	}
	if this.SubscriptionReservePercent != that1.SubscriptionReservePercent {
		return false
	}
	if this.RelayMinGasPrice != that1.RelayMinGasPrice {
		return false
	}
	if this.RelayMaxGasFee != that1.RelayMaxGasFee {
		return false
	}
	if this.MaxEnvelopeAge != that1.MaxEnvelopeAge {
		return false
	}
	if this.PowDifficultyStep != that1.PowDifficultyStep {
		return false
	}
	if len(this.AwardConfigs) != len(that1.AwardConfigs) {
		return false
	}
	for i := range this.AwardConfigs {
		if !this.AwardConfigs[i].Equal(that1.AwardConfigs[i]) {
			return false
		}
	}
	return true
}
func (this *AwardConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AwardConfig)
	if !ok {
		that2, ok := that.(AwardConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Cost != that1.Cost {
		return false
	}
	return true
}
func (m *TierConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TierConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TierConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxBiographyLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxBiographyLength))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.CanHaveFlair {
		i--
		if m.CanHaveFlair {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.CanHaveBanner {
		i--
		if m.CanHaveBanner {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.CanHaveAvatar {
		i--
		if m.CanHaveAvatar {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.CanHaveBiography {
		i--
		if m.CanHaveBiography {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.CanRemoveAnon {
		i--
		if m.CanRemoveAnon {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.CanBeAgent {
		i--
		if m.CanBeAgent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x78
	}
	if m.VoteWeight != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.VoteWeight))))
		i--
		dAtA[i] = 0x69
	}
	if m.EditingTimeMins != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EditingTimeMins))
		i--
		dAtA[i] = 0x50
	}
	if m.MaxContentLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxContentLength))
		i--
		dAtA[i] = 0x48
	}
	if m.MaxTitleLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxTitleLength))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxBlockedTopics != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxBlockedTopics))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxBlockedPosts != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxBlockedPosts))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxBlockedUsers != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxBlockedUsers))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxFollowedTopics != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxFollowedTopics))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxFollowedUsers != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxFollowedUsers))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxEnabledAgents != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxEnabledAgents))
		i--
		dAtA[i] = 0x10
	}
	if m.PeriodFee != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PeriodFee))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AwardConfigs) > 0 {
		for iNdEx := len(m.AwardConfigs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AwardConfigs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3
			i--
			dAtA[i] = 0xaa
		}
	}
	if m.PowDifficultyStep != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.PowDifficultyStep))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xa1
	}
	if m.MaxEnvelopeAge != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxEnvelopeAge))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xe8
	}
	if m.RelayMaxGasFee != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RelayMaxGasFee))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xe0
	}
	if m.RelayMinGasPrice != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RelayMinGasPrice))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xd8
	}
	if m.SubscriptionReservePercent != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.SubscriptionReservePercent))))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xd1
	}
	if len(m.Tiers) > 0 {
		for iNdEx := len(m.Tiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2
			i--
			dAtA[i] = 0xca
		}
	}
	if m.SubscriptionPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SubscriptionPeriod))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xc0
	}
	if m.MintDynamicSplit != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.MintDynamicSplit))))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xb9
	}
	if m.MintDynamicCreditCap != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MintDynamicCreditCap))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xb0
	}
	if m.MinTopicSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinTopicSize))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xa8
	}
	if m.MinUsernameSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinUsernameSize))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xa0
	}
	if m.MaxTopicSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxTopicSize))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x98
	}
	if m.MaxUsernameSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxUsernameSize))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x90
	}
	if m.PowDifficultyAllowance != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PowDifficultyAllowance))
		i--
		dAtA[i] = 0x50
	}
	if m.BlockHashWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BlockHashWindow))
		i--
		dAtA[i] = 0x48
	}
	if m.MintQuantity != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MintQuantity))
		i--
		dAtA[i] = 0x40
	}
	if m.MintInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MintInterval))
		i--
		dAtA[i] = 0x38
	}
	if m.PowCalmSequenceThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PowCalmSequenceThreshold))
		i--
		dAtA[i] = 0x28
	}
	if m.PowCalmPeriodDefinition != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PowCalmPeriodDefinition))
		i--
		dAtA[i] = 0x20
	}
	if m.PowMessageLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PowMessageLimit))
		i--
		dAtA[i] = 0x18
	}
	if m.PowMessageWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PowMessageWindow))
		i--
		dAtA[i] = 0x10
	}
	if m.MinDifficulty != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinDifficulty))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AwardConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AwardConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AwardConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cost != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Cost))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TierConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PeriodFee != 0 {
		n += 1 + sovParams(uint64(m.PeriodFee))
	}
	if m.MaxEnabledAgents != 0 {
		n += 1 + sovParams(uint64(m.MaxEnabledAgents))
	}
	if m.MaxFollowedUsers != 0 {
		n += 1 + sovParams(uint64(m.MaxFollowedUsers))
	}
	if m.MaxFollowedTopics != 0 {
		n += 1 + sovParams(uint64(m.MaxFollowedTopics))
	}
	if m.MaxBlockedUsers != 0 {
		n += 1 + sovParams(uint64(m.MaxBlockedUsers))
	}
	if m.MaxBlockedPosts != 0 {
		n += 1 + sovParams(uint64(m.MaxBlockedPosts))
	}
	if m.MaxBlockedTopics != 0 {
		n += 1 + sovParams(uint64(m.MaxBlockedTopics))
	}
	if m.MaxTitleLength != 0 {
		n += 1 + sovParams(uint64(m.MaxTitleLength))
	}
	if m.MaxContentLength != 0 {
		n += 1 + sovParams(uint64(m.MaxContentLength))
	}
	if m.EditingTimeMins != 0 {
		n += 1 + sovParams(uint64(m.EditingTimeMins))
	}
	if m.VoteWeight != 0 {
		n += 9
	}
	if m.CanBeAgent {
		n += 2
	}
	if m.CanRemoveAnon {
		n += 3
	}
	if m.CanHaveBiography {
		n += 3
	}
	if m.CanHaveAvatar {
		n += 3
	}
	if m.CanHaveBanner {
		n += 3
	}
	if m.CanHaveFlair {
		n += 3
	}
	if m.MaxBiographyLength != 0 {
		n += 2 + sovParams(uint64(m.MaxBiographyLength))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinDifficulty != 0 {
		n += 1 + sovParams(uint64(m.MinDifficulty))
	}
	if m.PowMessageWindow != 0 {
		n += 1 + sovParams(uint64(m.PowMessageWindow))
	}
	if m.PowMessageLimit != 0 {
		n += 1 + sovParams(uint64(m.PowMessageLimit))
	}
	if m.PowCalmPeriodDefinition != 0 {
		n += 1 + sovParams(uint64(m.PowCalmPeriodDefinition))
	}
	if m.PowCalmSequenceThreshold != 0 {
		n += 1 + sovParams(uint64(m.PowCalmSequenceThreshold))
	}
	if m.MintInterval != 0 {
		n += 1 + sovParams(uint64(m.MintInterval))
	}
	if m.MintQuantity != 0 {
		n += 1 + sovParams(uint64(m.MintQuantity))
	}
	if m.BlockHashWindow != 0 {
		n += 1 + sovParams(uint64(m.BlockHashWindow))
	}
	if m.PowDifficultyAllowance != 0 {
		n += 1 + sovParams(uint64(m.PowDifficultyAllowance))
	}
	if m.MaxUsernameSize != 0 {
		n += 2 + sovParams(uint64(m.MaxUsernameSize))
	}
	if m.MaxTopicSize != 0 {
		n += 2 + sovParams(uint64(m.MaxTopicSize))
	}
	if m.MinUsernameSize != 0 {
		n += 2 + sovParams(uint64(m.MinUsernameSize))
	}
	if m.MinTopicSize != 0 {
		n += 2 + sovParams(uint64(m.MinTopicSize))
	}
	if m.MintDynamicCreditCap != 0 {
		n += 2 + sovParams(uint64(m.MintDynamicCreditCap))
	}
	if m.MintDynamicSplit != 0 {
		n += 10
	}
	if m.SubscriptionPeriod != 0 {
		n += 2 + sovParams(uint64(m.SubscriptionPeriod))
	}
	if len(m.Tiers) > 0 {
		for _, e := range m.Tiers {
			l = e.Size()
			n += 2 + l + sovParams(uint64(l))
		}
	}
	if m.SubscriptionReservePercent != 0 {
		n += 10
	}
	if m.RelayMinGasPrice != 0 {
		n += 2 + sovParams(uint64(m.RelayMinGasPrice))
	}
	if m.RelayMaxGasFee != 0 {
		n += 2 + sovParams(uint64(m.RelayMaxGasFee))
	}
	if m.MaxEnvelopeAge != 0 {
		n += 2 + sovParams(uint64(m.MaxEnvelopeAge))
	}
	if m.PowDifficultyStep != 0 {
		n += 10
	}
	if len(m.AwardConfigs) > 0 {
		for _, e := range m.AwardConfigs {
			l = e.Size()
			n += 2 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *AwardConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.Cost != 0 {
		n += 1 + sovParams(uint64(m.Cost))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TierConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TierConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TierConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodFee", wireType)
			}
			m.PeriodFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeriodFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxEnabledAgents", wireType)
			}
			m.MaxEnabledAgents = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxEnabledAgents |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFollowedUsers", wireType)
			}
			m.MaxFollowedUsers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxFollowedUsers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFollowedTopics", wireType)
			}
			m.MaxFollowedTopics = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxFollowedTopics |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBlockedUsers", wireType)
			}
			m.MaxBlockedUsers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBlockedUsers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBlockedPosts", wireType)
			}
			m.MaxBlockedPosts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBlockedPosts |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBlockedTopics", wireType)
			}
			m.MaxBlockedTopics = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBlockedTopics |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTitleLength", wireType)
			}
			m.MaxTitleLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTitleLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxContentLength", wireType)
			}
			m.MaxContentLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxContentLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EditingTimeMins", wireType)
			}
			m.EditingTimeMins = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EditingTimeMins |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteWeight", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.VoteWeight = float64(math.Float64frombits(v))
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanBeAgent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CanBeAgent = bool(v != 0)
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanRemoveAnon", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CanRemoveAnon = bool(v != 0)
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanHaveBiography", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CanHaveBiography = bool(v != 0)
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanHaveAvatar", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CanHaveAvatar = bool(v != 0)
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanHaveBanner", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CanHaveBanner = bool(v != 0)
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanHaveFlair", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CanHaveFlair = bool(v != 0)
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBiographyLength", wireType)
			}
			m.MaxBiographyLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBiographyLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDifficulty", wireType)
			}
			m.MinDifficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDifficulty |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowMessageWindow", wireType)
			}
			m.PowMessageWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PowMessageWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowMessageLimit", wireType)
			}
			m.PowMessageLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PowMessageLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowCalmPeriodDefinition", wireType)
			}
			m.PowCalmPeriodDefinition = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PowCalmPeriodDefinition |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowCalmSequenceThreshold", wireType)
			}
			m.PowCalmSequenceThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PowCalmSequenceThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintInterval", wireType)
			}
			m.MintInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MintInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintQuantity", wireType)
			}
			m.MintQuantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MintQuantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHashWindow", wireType)
			}
			m.BlockHashWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHashWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowDifficultyAllowance", wireType)
			}
			m.PowDifficultyAllowance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PowDifficultyAllowance |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 34:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxUsernameSize", wireType)
			}
			m.MaxUsernameSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxUsernameSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 35:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTopicSize", wireType)
			}
			m.MaxTopicSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTopicSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 36:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinUsernameSize", wireType)
			}
			m.MinUsernameSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinUsernameSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 37:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinTopicSize", wireType)
			}
			m.MinTopicSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinTopicSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 38:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintDynamicCreditCap", wireType)
			}
			m.MintDynamicCreditCap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MintDynamicCreditCap |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 39:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintDynamicSplit", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.MintDynamicSplit = float64(math.Float64frombits(v))
		case 40:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionPeriod", wireType)
			}
			m.SubscriptionPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 41:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tiers = append(m.Tiers, &TierConfig{})
			if err := m.Tiers[len(m.Tiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 42:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionReservePercent", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.SubscriptionReservePercent = float64(math.Float64frombits(v))
		case 43:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayMinGasPrice", wireType)
			}
			m.RelayMinGasPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RelayMinGasPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 44:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayMaxGasFee", wireType)
			}
			m.RelayMaxGasFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RelayMaxGasFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 45:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxEnvelopeAge", wireType)
			}
			m.MaxEnvelopeAge = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxEnvelopeAge |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 52:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowDifficultyStep", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.PowDifficultyStep = float64(math.Float64frombits(v))
		case 53:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AwardConfigs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AwardConfigs = append(m.AwardConfigs, &AwardConfig{})
			if err := m.AwardConfigs[len(m.AwardConfigs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AwardConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AwardConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AwardConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			m.Cost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
