// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mirage/core/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryDifficultyRequest is request type for the Query/Difficulty RPC method.
type QueryDifficultyRequest struct {
}

func (m *QueryDifficultyRequest) Reset()         { *m = QueryDifficultyRequest{} }
func (m *QueryDifficultyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDifficultyRequest) ProtoMessage()    {}
func (*QueryDifficultyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{2}
}
func (m *QueryDifficultyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDifficultyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDifficultyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDifficultyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDifficultyRequest.Merge(m, src)
}
func (m *QueryDifficultyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDifficultyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDifficultyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDifficultyRequest proto.InternalMessageInfo

// QueryDifficultyResponse is response type for the Query/Difficulty RPC method.
type QueryDifficultyResponse struct {
	// current_difficulty is the current PoW difficulty step (0 = base, 1 = +step, 2 = +step^2, ...)
	CurrentDifficulty uint64 `protobuf:"varint,1,opt,name=current_difficulty,json=currentDifficulty,proto3" json:"current_difficulty,omitempty"`
	// previous_difficulty is the difficulty step before the last change
	PreviousDifficulty uint64 `protobuf:"varint,2,opt,name=previous_difficulty,json=previousDifficulty,proto3" json:"previous_difficulty,omitempty"`
	// last_change_height is the block height when difficulty last changed
	LastChangeHeight int64 `protobuf:"varint,3,opt,name=last_change_height,json=lastChangeHeight,proto3" json:"last_change_height,omitempty"`
	// pow_message_count is the number of PoW messages in the current window
	PowMessageCount uint64 `protobuf:"varint,4,opt,name=pow_message_count,json=powMessageCount,proto3" json:"pow_message_count,omitempty"`
	// consecutive_low_usage is the count of consecutive calm periods
	ConsecutiveLowUsage uint64 `protobuf:"varint,5,opt,name=consecutive_low_usage,json=consecutiveLowUsage,proto3" json:"consecutive_low_usage,omitempty"`
	// latest_block_hash is the most recent committed block hash (hex, lowercase)
	LatestBlockHash string `protobuf:"bytes,6,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`
	// current_height is the current block height
	CurrentHeight int64 `protobuf:"varint,7,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	// min_difficulty is the base difficulty (leading zero bits) used to compute the PoW target
	MinDifficulty uint64 `protobuf:"varint,8,opt,name=min_difficulty,json=minDifficulty,proto3" json:"min_difficulty,omitempty"`
}

func (m *QueryDifficultyResponse) Reset()         { *m = QueryDifficultyResponse{} }
func (m *QueryDifficultyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDifficultyResponse) ProtoMessage()    {}
func (*QueryDifficultyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{3}
}
func (m *QueryDifficultyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDifficultyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDifficultyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDifficultyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDifficultyResponse.Merge(m, src)
}
func (m *QueryDifficultyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDifficultyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDifficultyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDifficultyResponse proto.InternalMessageInfo

func (m *QueryDifficultyResponse) GetCurrentDifficulty() uint64 {
	if m != nil {
		return m.CurrentDifficulty
	}
	return 0
}

func (m *QueryDifficultyResponse) GetPreviousDifficulty() uint64 {
	if m != nil {
		return m.PreviousDifficulty
	}
	return 0
}

func (m *QueryDifficultyResponse) GetLastChangeHeight() int64 {
	if m != nil {
		return m.LastChangeHeight
	}
	return 0
}

func (m *QueryDifficultyResponse) GetPowMessageCount() uint64 {
	if m != nil {
		return m.PowMessageCount
	}
	return 0
}

func (m *QueryDifficultyResponse) GetConsecutiveLowUsage() uint64 {
	if m != nil {
		return m.ConsecutiveLowUsage
	}
	return 0
}

func (m *QueryDifficultyResponse) GetLatestBlockHash() string {
	if m != nil {
		return m.LatestBlockHash
	}
	return ""
}

func (m *QueryDifficultyResponse) GetCurrentHeight() int64 {
	if m != nil {
		return m.CurrentHeight
	}
	return 0
}

func (m *QueryDifficultyResponse) GetMinDifficulty() uint64 {
	if m != nil {
		return m.MinDifficulty
	}
	return 0
}

// QueryProfileRequest is the request type for the Query/Profile RPC method.
type QueryProfileRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryProfileRequest) Reset()         { *m = QueryProfileRequest{} }
func (m *QueryProfileRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProfileRequest) ProtoMessage()    {}
func (*QueryProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{4}
}
func (m *QueryProfileRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProfileRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProfileRequest.Merge(m, src)
}
func (m *QueryProfileRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProfileRequest proto.InternalMessageInfo

func (m *QueryProfileRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryProfileResponse is the response type for the Query/Profile RPC method.
type QueryProfileResponse struct {
	Owner              string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Username           string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Level              int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	CreatedAt          int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SubscriptionExpiry int64  `protobuf:"varint,5,opt,name=subscription_expiry,json=subscriptionExpiry,proto3" json:"subscription_expiry,omitempty"`
	AutoRenew          bool   `protobuf:"varint,6,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	ReserveFunds       uint64 `protobuf:"varint,7,opt,name=reserve_funds,json=reserveFunds,proto3" json:"reserve_funds,omitempty"`
	Biography          string `protobuf:"bytes,9,opt,name=biography,proto3" json:"biography,omitempty"`
	Avatar             string `protobuf:"bytes,10,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Banner             string `protobuf:"bytes,11,opt,name=banner,proto3" json:"banner,omitempty"`
	Flair              string `protobuf:"bytes,18,opt,name=flair,proto3" json:"flair,omitempty"`
	// Lists (stored separately but returned together for convenience)
	EnabledAgents  []string `protobuf:"bytes,12,rep,name=enabled_agents,json=enabledAgents,proto3" json:"enabled_agents,omitempty"`
	FollowedUsers  []string `protobuf:"bytes,13,rep,name=followed_users,json=followedUsers,proto3" json:"followed_users,omitempty"`
	FollowedTopics []string `protobuf:"bytes,14,rep,name=followed_topics,json=followedTopics,proto3" json:"followed_topics,omitempty"`
	BlockedUsers   []string `protobuf:"bytes,15,rep,name=blocked_users,json=blockedUsers,proto3" json:"blocked_users,omitempty"`
	BlockedPosts   []string `protobuf:"bytes,16,rep,name=blocked_posts,json=blockedPosts,proto3" json:"blocked_posts,omitempty"`
	BlockedTopics  []string `protobuf:"bytes,17,rep,name=blocked_topics,json=blockedTopics,proto3" json:"blocked_topics,omitempty"`
}

func (m *QueryProfileResponse) Reset()         { *m = QueryProfileResponse{} }
func (m *QueryProfileResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProfileResponse) ProtoMessage()    {}
func (*QueryProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{5}
}
func (m *QueryProfileResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProfileResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProfileResponse.Merge(m, src)
}
func (m *QueryProfileResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProfileResponse proto.InternalMessageInfo

func (m *QueryProfileResponse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *QueryProfileResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryProfileResponse) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *QueryProfileResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *QueryProfileResponse) GetSubscriptionExpiry() int64 {
	if m != nil {
		return m.SubscriptionExpiry
	}
	return 0
}

func (m *QueryProfileResponse) GetAutoRenew() bool {
	if m != nil {
		return m.AutoRenew
	}
	return false
}

func (m *QueryProfileResponse) GetReserveFunds() uint64 {
	if m != nil {
		return m.ReserveFunds
	}
	return 0
}

func (m *QueryProfileResponse) GetBiography() string {
	if m != nil {
		return m.Biography
	}
	return ""
}

func (m *QueryProfileResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *QueryProfileResponse) GetBanner() string {
	if m != nil {
		return m.Banner
	}
	return ""
}

func (m *QueryProfileResponse) GetFlair() string {
	if m != nil {
		return m.Flair
	}
	return ""
}

func (m *QueryProfileResponse) GetEnabledAgents() []string {
	if m != nil {
		return m.EnabledAgents
	}
	return nil
}

func (m *QueryProfileResponse) GetFollowedUsers() []string {
	if m != nil {
		return m.FollowedUsers
	}
	return nil
}

func (m *QueryProfileResponse) GetFollowedTopics() []string {
	if m != nil {
		return m.FollowedTopics
	}
	return nil
}

func (m *QueryProfileResponse) GetBlockedUsers() []string {
	if m != nil {
		return m.BlockedUsers
	}
	return nil
}

func (m *QueryProfileResponse) GetBlockedPosts() []string {
	if m != nil {
		return m.BlockedPosts
	}
	return nil
}

func (m *QueryProfileResponse) GetBlockedTopics() []string {
	if m != nil {
		return m.BlockedTopics
	}
	return nil
}

// QueryProfilesRequest is the request type for the Query/Profiles RPC method.
type QueryProfilesRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryProfilesRequest) Reset()         { *m = QueryProfilesRequest{} }
func (m *QueryProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProfilesRequest) ProtoMessage()    {}
func (*QueryProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{6}
}
func (m *QueryProfilesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProfilesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProfilesRequest.Merge(m, src)
}
func (m *QueryProfilesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProfilesRequest proto.InternalMessageInfo

func (m *QueryProfilesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryProfilesResponse is the response type for the Query/Profiles RPC method.
type QueryProfilesResponse struct {
	Profiles   []*QueryProfileResponse `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Pagination *query.PageResponse     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryProfilesResponse) Reset()         { *m = QueryProfilesResponse{} }
func (m *QueryProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProfilesResponse) ProtoMessage()    {}
func (*QueryProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{7}
}
func (m *QueryProfilesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProfilesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProfilesResponse.Merge(m, src)
}
func (m *QueryProfilesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProfilesResponse proto.InternalMessageInfo

func (m *QueryProfilesResponse) GetProfiles() []*QueryProfileResponse {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func (m *QueryProfilesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mirage.core.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mirage.core.v1.QueryParamsResponse")
	proto.RegisterType((*QueryDifficultyRequest)(nil), "mirage.core.v1.QueryDifficultyRequest")
	proto.RegisterType((*QueryDifficultyResponse)(nil), "mirage.core.v1.QueryDifficultyResponse")
	proto.RegisterType((*QueryProfileRequest)(nil), "mirage.core.v1.QueryProfileRequest")
	proto.RegisterType((*QueryProfileResponse)(nil), "mirage.core.v1.QueryProfileResponse")
	proto.RegisterType((*QueryProfilesRequest)(nil), "mirage.core.v1.QueryProfilesRequest")
	proto.RegisterType((*QueryProfilesResponse)(nil), "mirage.core.v1.QueryProfilesResponse")
}

func init() { proto.RegisterFile("mirage/core/v1/query.proto", fileDescriptor_c69a11bcea5c6b00) }

var fileDescriptor_c69a11bcea5c6b00 = []byte{
	// 994 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0xae, 0x9b, 0xb4, 0x1b, 0x4f, 0x9b, 0xfe, 0x98, 0x76, 0x8b, 0x15, 0x4a, 0x08, 0x2e, 0xdd,
	0x86, 0x8a, 0x8d, 0xd5, 0x72, 0xe2, 0xc6, 0x76, 0x61, 0xbb, 0x42, 0x20, 0x15, 0x8b, 0xbd, 0x70,
	0xc0, 0x9a, 0x38, 0x2f, 0x8e, 0x85, 0xe3, 0xf1, 0xce, 0x8c, 0x93, 0x8d, 0x80, 0x03, 0x2b, 0x24,
	0xae, 0x48, 0xfc, 0x07, 0x9c, 0x38, 0xf2, 0x47, 0x70, 0xd8, 0x63, 0x25, 0x2e, 0x9c, 0x10, 0x6a,
	0x91, 0xf8, 0x37, 0xd0, 0xfc, 0x70, 0xe2, 0xb4, 0xa5, 0xe5, 0x12, 0x65, 0xbe, 0xef, 0x7b, 0xef,
	0x7d, 0xf3, 0xde, 0xe8, 0x19, 0x35, 0x86, 0x31, 0x23, 0x11, 0x78, 0x21, 0x65, 0xe0, 0x8d, 0x8e,
	0xbc, 0xe7, 0x39, 0xb0, 0x49, 0x27, 0x63, 0x54, 0x50, 0xbc, 0xa6, 0xb9, 0x8e, 0xe4, 0x3a, 0xa3,
	0xa3, 0xc6, 0x26, 0x19, 0xc6, 0x29, 0xf5, 0xd4, 0xaf, 0x96, 0x34, 0xb6, 0x23, 0x1a, 0x51, 0xf5,
	0xd7, 0x93, 0xff, 0x0c, 0xba, 0x1b, 0x51, 0x1a, 0x25, 0xe0, 0x91, 0x2c, 0xf6, 0x48, 0x9a, 0x52,
	0x41, 0x44, 0x4c, 0x53, 0x6e, 0xd8, 0xc3, 0x90, 0xf2, 0x21, 0xe5, 0x5e, 0x97, 0x70, 0xd0, 0xf5,
	0xbc, 0xd1, 0x51, 0x17, 0x04, 0x39, 0xf2, 0x32, 0x12, 0xc5, 0xa9, 0x12, 0x1b, 0xed, 0xeb, 0x57,
	0xec, 0x65, 0x84, 0x91, 0xa1, 0x49, 0xe4, 0x6e, 0x23, 0xfc, 0x99, 0x0c, 0x3f, 0x53, 0xa0, 0x0f,
	0xcf, 0x73, 0xe0, 0xc2, 0x3d, 0x43, 0x5b, 0x73, 0x28, 0xcf, 0x68, 0xca, 0x01, 0xbf, 0x8f, 0x96,
	0x75, 0xb0, 0x63, 0xb5, 0xac, 0xf6, 0xca, 0xf1, 0x4e, 0x67, 0xfe, 0x76, 0x1d, 0xad, 0x3f, 0xb1,
	0x5f, 0xfd, 0xf9, 0xe6, 0xc2, 0x2f, 0xff, 0xfc, 0x7a, 0x68, 0xf9, 0x26, 0xc0, 0x75, 0xd0, 0x8e,
	0xca, 0xf8, 0x61, 0xdc, 0xef, 0xc7, 0x61, 0x9e, 0x88, 0x49, 0x51, 0xeb, 0xbb, 0x0a, 0x7a, 0xed,
	0x1a, 0x65, 0x0a, 0x3e, 0x44, 0x38, 0xcc, 0x19, 0x83, 0x54, 0x04, 0xbd, 0x29, 0xab, 0x8a, 0x57,
	0xfd, 0x4d, 0xc3, 0xcc, 0xc2, 0xb0, 0x87, 0xb6, 0x32, 0x06, 0xa3, 0x98, 0xe6, 0xbc, 0xac, 0x5f,
	0x54, 0x7a, 0x5c, 0x50, 0xa5, 0x80, 0x77, 0x11, 0x4e, 0x08, 0x17, 0x41, 0x38, 0x20, 0x69, 0x04,
	0xc1, 0x00, 0xe2, 0x68, 0x20, 0x9c, 0x4a, 0xcb, 0x6a, 0x57, 0xfc, 0x0d, 0xc9, 0x3c, 0x56, 0xc4,
	0x53, 0x85, 0xe3, 0x43, 0xb4, 0x99, 0xd1, 0x71, 0x30, 0x04, 0xce, 0x49, 0x04, 0x41, 0x48, 0xf3,
	0x54, 0x38, 0x55, 0x95, 0x7c, 0x3d, 0xa3, 0xe3, 0x4f, 0x35, 0xfe, 0x58, 0xc2, 0xf8, 0x18, 0xdd,
	0x0f, 0xe5, 0x15, 0xc2, 0x5c, 0xc4, 0x23, 0x08, 0x12, 0x3a, 0x0e, 0x72, 0xc9, 0x3a, 0x4b, 0x4a,
	0xbf, 0x55, 0x22, 0x3f, 0xa1, 0xe3, 0x67, 0x92, 0x92, 0xf9, 0x13, 0x22, 0x80, 0x8b, 0xa0, 0x9b,
	0xd0, 0xf0, 0xab, 0x60, 0x40, 0xf8, 0xc0, 0x59, 0x6e, 0x59, 0x6d, 0xdb, 0x5f, 0xd7, 0xc4, 0x89,
	0xc4, 0x9f, 0x12, 0x3e, 0xc0, 0xfb, 0x68, 0xad, 0xe8, 0x8c, 0x71, 0x7d, 0x4f, 0xb9, 0xae, 0x1b,
	0xd4, 0x58, 0xde, 0x47, 0x6b, 0xc3, 0x38, 0x2d, 0x37, 0xa3, 0xa6, 0xea, 0xd7, 0x87, 0x71, 0x3a,
	0xeb, 0x83, 0xeb, 0x15, 0xf3, 0x66, 0xb4, 0x1f, 0x27, 0x60, 0x46, 0x83, 0x1d, 0x74, 0x8f, 0xf4,
	0x7a, 0x0c, 0xb8, 0x1e, 0xb8, 0xed, 0x17, 0x47, 0xf7, 0xb7, 0x2a, 0xda, 0x9e, 0x8f, 0x30, 0x13,
	0xdb, 0x46, 0x4b, 0x74, 0x9c, 0x02, 0x33, 0x01, 0xfa, 0x80, 0x1b, 0xa8, 0x96, 0x73, 0x60, 0x29,
	0x19, 0x82, 0x9a, 0x86, 0xed, 0x4f, 0xcf, 0x32, 0x22, 0x81, 0x11, 0x24, 0xaa, 0xed, 0x4b, 0xbe,
	0x3e, 0xe0, 0x37, 0x10, 0x0a, 0x19, 0x10, 0x01, 0xbd, 0x80, 0xe8, 0x26, 0x57, 0x7c, 0xdb, 0x20,
	0x8f, 0x84, 0x9c, 0x34, 0xcf, 0xbb, 0x3c, 0x64, 0x71, 0x26, 0x5f, 0x7a, 0x00, 0x2f, 0xb2, 0x98,
	0x4d, 0x54, 0x73, 0x2b, 0x3e, 0x2e, 0x53, 0x1f, 0x29, 0x46, 0xe6, 0x23, 0xb9, 0xa0, 0x01, 0x83,
	0x14, 0xc6, 0xaa, 0xa9, 0x35, 0xdf, 0x96, 0x88, 0x2f, 0x01, 0xbc, 0x87, 0xea, 0x0c, 0x38, 0xb0,
	0x11, 0x04, 0xfd, 0x3c, 0xed, 0x71, 0xd5, 0xcd, 0xaa, 0xbf, 0x6a, 0xc0, 0x27, 0x12, 0xc3, 0xbb,
	0xc8, 0xee, 0xc6, 0x34, 0x62, 0x24, 0x1b, 0x4c, 0x1c, 0x5b, 0x5d, 0x63, 0x06, 0xe0, 0x1d, 0xb4,
	0x4c, 0x46, 0x44, 0x10, 0xe6, 0x20, 0x45, 0x99, 0x93, 0xc4, 0xbb, 0x24, 0x95, 0x2d, 0x59, 0xd1,
	0xb8, 0x3e, 0xc9, 0x7b, 0xf7, 0x13, 0x12, 0x33, 0x07, 0xeb, 0x4e, 0xa9, 0x83, 0x1c, 0x18, 0xa4,
	0xa4, 0x9b, 0xc8, 0x7b, 0x47, 0x90, 0x0a, 0xee, 0xac, 0xb6, 0x2a, 0x6d, 0xdb, 0xaf, 0x1b, 0xf4,
	0x91, 0x02, 0xa5, 0xac, 0x4f, 0x93, 0x84, 0x8e, 0xa1, 0x17, 0xc8, 0x4e, 0x72, 0xa7, 0xae, 0x65,
	0x05, 0xfa, 0x4c, 0x82, 0xf8, 0x00, 0xad, 0x4f, 0x65, 0x82, 0x66, 0x71, 0xc8, 0x9d, 0x35, 0xa5,
	0x9b, 0x46, 0x7f, 0xae, 0x50, 0x79, 0x7f, 0xf5, 0xe6, 0xa6, 0xe9, 0xd6, 0x95, 0x6c, 0xd5, 0x80,
	0x3a, 0x5b, 0x49, 0x94, 0x51, 0x2e, 0xb8, 0xb3, 0x31, 0x27, 0x3a, 0x93, 0x98, 0x74, 0x56, 0x88,
	0x4c, 0xc5, 0x4d, 0xed, 0xcc, 0xa0, 0xba, 0xe0, 0xc7, 0xd5, 0x5a, 0x6d, 0xc3, 0x76, 0xbf, 0x9c,
	0x7f, 0x45, 0xc5, 0xfe, 0xc1, 0x4f, 0x10, 0x9a, 0xad, 0x31, 0xb3, 0x6c, 0x1e, 0x74, 0xf4, 0xce,
	0xeb, 0xc8, 0x9d, 0xd7, 0xd1, 0x3b, 0xd6, 0xec, 0xbc, 0xce, 0x19, 0x89, 0x8a, 0x47, 0xeb, 0x97,
	0x22, 0xdd, 0x9f, 0x2d, 0x74, 0xff, 0x4a, 0x01, 0xf3, 0x4e, 0x3f, 0x40, 0xb5, 0xcc, 0x60, 0x8e,
	0xd5, 0xaa, 0xb4, 0x57, 0x8e, 0xdf, 0xbe, 0xba, 0xcc, 0x6e, 0x7a, 0xdf, 0xfe, 0x34, 0x0a, 0x9f,
	0xce, 0x79, 0x5c, 0x54, 0x1e, 0x0f, 0xee, 0xf4, 0x68, 0xd2, 0x94, 0x42, 0x8f, 0x7f, 0xa8, 0xa2,
	0x25, 0x55, 0x0b, 0x0b, 0x64, 0x9f, 0x82, 0xd0, 0x4b, 0x14, 0xbb, 0x37, 0xfb, 0x29, 0xef, 0xe9,
	0xc6, 0xde, 0xad, 0x1a, 0x5d, 0xcb, 0x6d, 0xbe, 0xfc, 0xfd, 0xef, 0x9f, 0x16, 0x1d, 0xbc, 0xe3,
	0xdd, 0xf8, 0x21, 0xc0, 0xdf, 0x5b, 0xa8, 0x7e, 0x0a, 0xe5, 0x3d, 0xfa, 0xe0, 0xc6, 0xb4, 0xd7,
	0x56, 0x77, 0xe3, 0xe0, 0x4e, 0x9d, 0xb1, 0xe0, 0x2a, 0x0b, 0xbb, 0xb8, 0x71, 0xd5, 0xc2, 0x6c,
	0x31, 0xe1, 0x97, 0x16, 0x42, 0xf2, 0xf6, 0xba, 0xbf, 0x78, 0xef, 0xf6, 0x71, 0x68, 0x03, 0xff,
	0x6b, 0x66, 0xee, 0x3b, 0xaa, 0xfa, 0x1e, 0x7e, 0xeb, 0x5a, 0x03, 0xb4, 0xd0, 0xfb, 0xda, 0xac,
	0xb5, 0x6f, 0xf1, 0x37, 0x68, 0x65, 0xe6, 0x81, 0xe3, 0x5b, 0xf3, 0x4f, 0xa7, 0xb0, 0x7f, 0x87,
	0xca, 0xd8, 0x68, 0x29, 0x1b, 0x0d, 0xec, 0xfc, 0x87, 0x0d, 0x7e, 0xf2, 0xf0, 0xd5, 0x45, 0xd3,
	0x3a, 0xbf, 0x68, 0x5a, 0x7f, 0x5d, 0x34, 0xad, 0x1f, 0x2f, 0x9b, 0x0b, 0xe7, 0x97, 0xcd, 0x85,
	0x3f, 0x2e, 0x9b, 0x0b, 0x5f, 0x6c, 0x99, 0x90, 0x17, 0x3a, 0x48, 0x4c, 0x32, 0xe0, 0xdd, 0x65,
	0xf5, 0x09, 0x7f, 0xef, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0x50, 0x5f, 0x26, 0x80, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GetParams queries the parameters of the module.
	GetParams(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// GetDifficulty queries the current PoW difficulty state.
	GetDifficulty(ctx context.Context, in *QueryDifficultyRequest, opts ...grpc.CallOption) (*QueryDifficultyResponse, error)
	// GetProfile queries a profile by address.
	GetProfile(ctx context.Context, in *QueryProfileRequest, opts ...grpc.CallOption) (*QueryProfileResponse, error)
	// GetProfiles queries all profiles with pagination.
	GetProfiles(ctx context.Context, in *QueryProfilesRequest, opts ...grpc.CallOption) (*QueryProfilesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetParams(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mirage.core.v1.Query/GetParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDifficulty(ctx context.Context, in *QueryDifficultyRequest, opts ...grpc.CallOption) (*QueryDifficultyResponse, error) {
	out := new(QueryDifficultyResponse)
	err := c.cc.Invoke(ctx, "/mirage.core.v1.Query/GetDifficulty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProfile(ctx context.Context, in *QueryProfileRequest, opts ...grpc.CallOption) (*QueryProfileResponse, error) {
	out := new(QueryProfileResponse)
	err := c.cc.Invoke(ctx, "/mirage.core.v1.Query/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProfiles(ctx context.Context, in *QueryProfilesRequest, opts ...grpc.CallOption) (*QueryProfilesResponse, error) {
	out := new(QueryProfilesResponse)
	err := c.cc.Invoke(ctx, "/mirage.core.v1.Query/GetProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GetParams queries the parameters of the module.
	GetParams(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// GetDifficulty queries the current PoW difficulty state.
	GetDifficulty(context.Context, *QueryDifficultyRequest) (*QueryDifficultyResponse, error)
	// GetProfile queries a profile by address.
	GetProfile(context.Context, *QueryProfileRequest) (*QueryProfileResponse, error)
	// GetProfiles queries all profiles with pagination.
	GetProfiles(context.Context, *QueryProfilesRequest) (*QueryProfilesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetParams(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParams not implemented")
}
func (*UnimplementedQueryServer) GetDifficulty(ctx context.Context, req *QueryDifficultyRequest) (*QueryDifficultyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDifficulty not implemented")
}
func (*UnimplementedQueryServer) GetProfile(ctx context.Context, req *QueryProfileRequest) (*QueryProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (*UnimplementedQueryServer) GetProfiles(ctx context.Context, req *QueryProfilesRequest) (*QueryProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfiles not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mirage.core.v1.Query/GetParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetParams(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDifficulty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDifficultyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDifficulty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mirage.core.v1.Query/GetDifficulty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDifficulty(ctx, req.(*QueryDifficultyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mirage.core.v1.Query/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProfile(ctx, req.(*QueryProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mirage.core.v1.Query/GetProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProfiles(ctx, req.(*QueryProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mirage.core.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetParams",
			Handler:    _Query_GetParams_Handler,
		},
		{
			MethodName: "GetDifficulty",
			Handler:    _Query_GetDifficulty_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _Query_GetProfile_Handler,
		},
		{
			MethodName: "GetProfiles",
			Handler:    _Query_GetProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mirage/core/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryDifficultyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDifficultyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDifficultyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDifficultyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDifficultyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDifficultyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinDifficulty != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MinDifficulty))
		i--
		dAtA[i] = 0x40
	}
	if m.CurrentHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CurrentHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.LatestBlockHash) > 0 {
		i -= len(m.LatestBlockHash)
		copy(dAtA[i:], m.LatestBlockHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.LatestBlockHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.ConsecutiveLowUsage != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ConsecutiveLowUsage))
		i--
		dAtA[i] = 0x28
	}
	if m.PowMessageCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PowMessageCount))
		i--
		dAtA[i] = 0x20
	}
	if m.LastChangeHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LastChangeHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.PreviousDifficulty != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PreviousDifficulty))
		i--
		dAtA[i] = 0x10
	}
	if m.CurrentDifficulty != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CurrentDifficulty))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryProfileRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProfileRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProfileRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProfileResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProfileResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProfileResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Flair) > 0 {
		i -= len(m.Flair)
		copy(dAtA[i:], m.Flair)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Flair)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.BlockedTopics) > 0 {
		for iNdEx := len(m.BlockedTopics) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BlockedTopics[iNdEx])
			copy(dAtA[i:], m.BlockedTopics[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.BlockedTopics[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	}
	if len(m.BlockedPosts) > 0 {
		for iNdEx := len(m.BlockedPosts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BlockedPosts[iNdEx])
			copy(dAtA[i:], m.BlockedPosts[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.BlockedPosts[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if len(m.BlockedUsers) > 0 {
		for iNdEx := len(m.BlockedUsers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BlockedUsers[iNdEx])
			copy(dAtA[i:], m.BlockedUsers[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.BlockedUsers[iNdEx])))
			i--
			dAtA[i] = 0x7a
		}
	}
	if len(m.FollowedTopics) > 0 {
		for iNdEx := len(m.FollowedTopics) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FollowedTopics[iNdEx])
			copy(dAtA[i:], m.FollowedTopics[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.FollowedTopics[iNdEx])))
			i--
			dAtA[i] = 0x72
		}
	}
	if len(m.FollowedUsers) > 0 {
		for iNdEx := len(m.FollowedUsers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FollowedUsers[iNdEx])
			copy(dAtA[i:], m.FollowedUsers[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.FollowedUsers[iNdEx])))
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.EnabledAgents) > 0 {
		for iNdEx := len(m.EnabledAgents) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.EnabledAgents[iNdEx])
			copy(dAtA[i:], m.EnabledAgents[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.EnabledAgents[iNdEx])))
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.Banner) > 0 {
		i -= len(m.Banner)
		copy(dAtA[i:], m.Banner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Banner)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Avatar) > 0 {
		i -= len(m.Avatar)
		copy(dAtA[i:], m.Avatar)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Avatar)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Biography) > 0 {
		i -= len(m.Biography)
		copy(dAtA[i:], m.Biography)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Biography)))
		i--
		dAtA[i] = 0x4a
	}
	if m.ReserveFunds != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ReserveFunds))
		i--
		dAtA[i] = 0x38
	}
	if m.AutoRenew {
		i--
		if m.AutoRenew {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.SubscriptionExpiry != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.SubscriptionExpiry))
		i--
		dAtA[i] = 0x28
	}
	if m.CreatedAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	if m.Level != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Level))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProfilesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProfilesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProfilesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProfilesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProfilesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProfilesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Profiles) > 0 {
		for iNdEx := len(m.Profiles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Profiles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDifficultyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDifficultyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CurrentDifficulty != 0 {
		n += 1 + sovQuery(uint64(m.CurrentDifficulty))
	}
	if m.PreviousDifficulty != 0 {
		n += 1 + sovQuery(uint64(m.PreviousDifficulty))
	}
	if m.LastChangeHeight != 0 {
		n += 1 + sovQuery(uint64(m.LastChangeHeight))
	}
	if m.PowMessageCount != 0 {
		n += 1 + sovQuery(uint64(m.PowMessageCount))
	}
	if m.ConsecutiveLowUsage != 0 {
		n += 1 + sovQuery(uint64(m.ConsecutiveLowUsage))
	}
	l = len(m.LatestBlockHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.CurrentHeight != 0 {
		n += 1 + sovQuery(uint64(m.CurrentHeight))
	}
	if m.MinDifficulty != 0 {
		n += 1 + sovQuery(uint64(m.MinDifficulty))
	}
	return n
}

func (m *QueryProfileRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryProfileResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Level != 0 {
		n += 1 + sovQuery(uint64(m.Level))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovQuery(uint64(m.CreatedAt))
	}
	if m.SubscriptionExpiry != 0 {
		n += 1 + sovQuery(uint64(m.SubscriptionExpiry))
	}
	if m.AutoRenew {
		n += 2
	}
	if m.ReserveFunds != 0 {
		n += 1 + sovQuery(uint64(m.ReserveFunds))
	}
	l = len(m.Biography)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Banner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.EnabledAgents) > 0 {
		for _, s := range m.EnabledAgents {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.FollowedUsers) > 0 {
		for _, s := range m.FollowedUsers {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.FollowedTopics) > 0 {
		for _, s := range m.FollowedTopics {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.BlockedUsers) > 0 {
		for _, s := range m.BlockedUsers {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.BlockedPosts) > 0 {
		for _, s := range m.BlockedPosts {
			l = len(s)
			n += 2 + l + sovQuery(uint64(l))
		}
	}
	if len(m.BlockedTopics) > 0 {
		for _, s := range m.BlockedTopics {
			l = len(s)
			n += 2 + l + sovQuery(uint64(l))
		}
	}
	l = len(m.Flair)
	if l > 0 {
		n += 2 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryProfilesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryProfilesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Profiles) > 0 {
		for _, e := range m.Profiles {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDifficultyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDifficultyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDifficultyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDifficultyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDifficultyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDifficultyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentDifficulty", wireType)
			}
			m.CurrentDifficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentDifficulty |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousDifficulty", wireType)
			}
			m.PreviousDifficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviousDifficulty |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastChangeHeight", wireType)
			}
			m.LastChangeHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastChangeHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowMessageCount", wireType)
			}
			m.PowMessageCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PowMessageCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsecutiveLowUsage", wireType)
			}
			m.ConsecutiveLowUsage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsecutiveLowUsage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestBlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestBlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentHeight", wireType)
			}
			m.CurrentHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDifficulty", wireType)
			}
			m.MinDifficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDifficulty |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProfileRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProfileRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProfileRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProfileResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProfileResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProfileResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			m.Level = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionExpiry", wireType)
			}
			m.SubscriptionExpiry = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionExpiry |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoRenew", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AutoRenew = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveFunds", wireType)
			}
			m.ReserveFunds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReserveFunds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Biography", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Biography = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Banner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Banner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnabledAgents", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnabledAgents = append(m.EnabledAgents, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FollowedUsers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FollowedUsers = append(m.FollowedUsers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FollowedTopics", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FollowedTopics = append(m.FollowedTopics, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockedUsers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockedUsers = append(m.BlockedUsers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockedPosts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockedPosts = append(m.BlockedPosts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockedTopics", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockedTopics = append(m.BlockedTopics, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flair", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Flair = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProfilesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProfilesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProfilesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProfilesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProfilesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProfilesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Profiles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Profiles = append(m.Profiles, &QueryProfileResponse{})
			if err := m.Profiles[len(m.Profiles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
