// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mirage/core/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryDifficultyRequest is request type for the Query/Difficulty RPC method.
type QueryDifficultyRequest struct {
}

func (m *QueryDifficultyRequest) Reset()         { *m = QueryDifficultyRequest{} }
func (m *QueryDifficultyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDifficultyRequest) ProtoMessage()    {}
func (*QueryDifficultyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{2}
}
func (m *QueryDifficultyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDifficultyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDifficultyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDifficultyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDifficultyRequest.Merge(m, src)
}
func (m *QueryDifficultyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDifficultyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDifficultyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDifficultyRequest proto.InternalMessageInfo

// QueryDifficultyResponse is response type for the Query/Difficulty RPC method.
type QueryDifficultyResponse struct {
	// current_difficulty is the current PoW difficulty (leading zero bits required)
	CurrentDifficulty uint64 `protobuf:"varint,1,opt,name=current_difficulty,json=currentDifficulty,proto3" json:"current_difficulty,omitempty"`
	// previous_difficulty is the difficulty before the last change
	PreviousDifficulty uint64 `protobuf:"varint,2,opt,name=previous_difficulty,json=previousDifficulty,proto3" json:"previous_difficulty,omitempty"`
	// last_change_height is the block height when difficulty last changed
	LastChangeHeight int64 `protobuf:"varint,3,opt,name=last_change_height,json=lastChangeHeight,proto3" json:"last_change_height,omitempty"`
	// pow_message_count is the number of PoW messages in the current window
	PowMessageCount uint64 `protobuf:"varint,4,opt,name=pow_message_count,json=powMessageCount,proto3" json:"pow_message_count,omitempty"`
	// consecutive_low_usage is the count of consecutive calm periods
	ConsecutiveLowUsage uint64 `protobuf:"varint,5,opt,name=consecutive_low_usage,json=consecutiveLowUsage,proto3" json:"consecutive_low_usage,omitempty"`
	// latest_block_hash is the most recent committed block hash (hex, lowercase)
	LatestBlockHash string `protobuf:"bytes,6,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`
	// current_height is the current block height
	CurrentHeight int64 `protobuf:"varint,7,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
}

func (m *QueryDifficultyResponse) Reset()         { *m = QueryDifficultyResponse{} }
func (m *QueryDifficultyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDifficultyResponse) ProtoMessage()    {}
func (*QueryDifficultyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{3}
}
func (m *QueryDifficultyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDifficultyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDifficultyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDifficultyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDifficultyResponse.Merge(m, src)
}
func (m *QueryDifficultyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDifficultyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDifficultyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDifficultyResponse proto.InternalMessageInfo

func (m *QueryDifficultyResponse) GetCurrentDifficulty() uint64 {
	if m != nil {
		return m.CurrentDifficulty
	}
	return 0
}

func (m *QueryDifficultyResponse) GetPreviousDifficulty() uint64 {
	if m != nil {
		return m.PreviousDifficulty
	}
	return 0
}

func (m *QueryDifficultyResponse) GetLastChangeHeight() int64 {
	if m != nil {
		return m.LastChangeHeight
	}
	return 0
}

func (m *QueryDifficultyResponse) GetPowMessageCount() uint64 {
	if m != nil {
		return m.PowMessageCount
	}
	return 0
}

func (m *QueryDifficultyResponse) GetConsecutiveLowUsage() uint64 {
	if m != nil {
		return m.ConsecutiveLowUsage
	}
	return 0
}

func (m *QueryDifficultyResponse) GetLatestBlockHash() string {
	if m != nil {
		return m.LatestBlockHash
	}
	return ""
}

func (m *QueryDifficultyResponse) GetCurrentHeight() int64 {
	if m != nil {
		return m.CurrentHeight
	}
	return 0
}

// QueryProfileRequest is the request type for the Query/Profile RPC method.
type QueryProfileRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryProfileRequest) Reset()         { *m = QueryProfileRequest{} }
func (m *QueryProfileRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProfileRequest) ProtoMessage()    {}
func (*QueryProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{4}
}
func (m *QueryProfileRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProfileRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProfileRequest.Merge(m, src)
}
func (m *QueryProfileRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProfileRequest proto.InternalMessageInfo

func (m *QueryProfileRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryProfileResponse is the response type for the Query/Profile RPC method.
type QueryProfileResponse struct {
	Owner              string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Username           string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Level              int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	CreatedAt          int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SubscriptionExpiry int64  `protobuf:"varint,5,opt,name=subscription_expiry,json=subscriptionExpiry,proto3" json:"subscription_expiry,omitempty"`
	AutoRenew          bool   `protobuf:"varint,6,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	ReserveFunds       uint64 `protobuf:"varint,7,opt,name=reserve_funds,json=reserveFunds,proto3" json:"reserve_funds,omitempty"`
	IsModerator        bool   `protobuf:"varint,8,opt,name=is_moderator,json=isModerator,proto3" json:"is_moderator,omitempty"`
	Biography          string `protobuf:"bytes,9,opt,name=biography,proto3" json:"biography,omitempty"`
	Avatar             string `protobuf:"bytes,10,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Banner             string `protobuf:"bytes,11,opt,name=banner,proto3" json:"banner,omitempty"`
	// Lists (stored separately but returned together for convenience)
	FollowedModerators []string `protobuf:"bytes,12,rep,name=followed_moderators,json=followedModerators,proto3" json:"followed_moderators,omitempty"`
	FollowedUsers      []string `protobuf:"bytes,13,rep,name=followed_users,json=followedUsers,proto3" json:"followed_users,omitempty"`
	FollowedTopics     []string `protobuf:"bytes,14,rep,name=followed_topics,json=followedTopics,proto3" json:"followed_topics,omitempty"`
	BlockedUsers       []string `protobuf:"bytes,15,rep,name=blocked_users,json=blockedUsers,proto3" json:"blocked_users,omitempty"`
	BlockedPosts       []string `protobuf:"bytes,16,rep,name=blocked_posts,json=blockedPosts,proto3" json:"blocked_posts,omitempty"`
	QualityPosts       []string `protobuf:"bytes,17,rep,name=quality_posts,json=qualityPosts,proto3" json:"quality_posts,omitempty"`
}

func (m *QueryProfileResponse) Reset()         { *m = QueryProfileResponse{} }
func (m *QueryProfileResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProfileResponse) ProtoMessage()    {}
func (*QueryProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{5}
}
func (m *QueryProfileResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProfileResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProfileResponse.Merge(m, src)
}
func (m *QueryProfileResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProfileResponse proto.InternalMessageInfo

func (m *QueryProfileResponse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *QueryProfileResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryProfileResponse) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *QueryProfileResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *QueryProfileResponse) GetSubscriptionExpiry() int64 {
	if m != nil {
		return m.SubscriptionExpiry
	}
	return 0
}

func (m *QueryProfileResponse) GetAutoRenew() bool {
	if m != nil {
		return m.AutoRenew
	}
	return false
}

func (m *QueryProfileResponse) GetReserveFunds() uint64 {
	if m != nil {
		return m.ReserveFunds
	}
	return 0
}

func (m *QueryProfileResponse) GetIsModerator() bool {
	if m != nil {
		return m.IsModerator
	}
	return false
}

func (m *QueryProfileResponse) GetBiography() string {
	if m != nil {
		return m.Biography
	}
	return ""
}

func (m *QueryProfileResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *QueryProfileResponse) GetBanner() string {
	if m != nil {
		return m.Banner
	}
	return ""
}

func (m *QueryProfileResponse) GetFollowedModerators() []string {
	if m != nil {
		return m.FollowedModerators
	}
	return nil
}

func (m *QueryProfileResponse) GetFollowedUsers() []string {
	if m != nil {
		return m.FollowedUsers
	}
	return nil
}

func (m *QueryProfileResponse) GetFollowedTopics() []string {
	if m != nil {
		return m.FollowedTopics
	}
	return nil
}

func (m *QueryProfileResponse) GetBlockedUsers() []string {
	if m != nil {
		return m.BlockedUsers
	}
	return nil
}

func (m *QueryProfileResponse) GetBlockedPosts() []string {
	if m != nil {
		return m.BlockedPosts
	}
	return nil
}

func (m *QueryProfileResponse) GetQualityPosts() []string {
	if m != nil {
		return m.QualityPosts
	}
	return nil
}

// QueryProfilesRequest is the request type for the Query/Profiles RPC method.
type QueryProfilesRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryProfilesRequest) Reset()         { *m = QueryProfilesRequest{} }
func (m *QueryProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProfilesRequest) ProtoMessage()    {}
func (*QueryProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{6}
}
func (m *QueryProfilesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProfilesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProfilesRequest.Merge(m, src)
}
func (m *QueryProfilesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProfilesRequest proto.InternalMessageInfo

func (m *QueryProfilesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryProfilesResponse is the response type for the Query/Profiles RPC method.
type QueryProfilesResponse struct {
	Profiles   []*QueryProfileResponse `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Pagination *query.PageResponse     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryProfilesResponse) Reset()         { *m = QueryProfilesResponse{} }
func (m *QueryProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProfilesResponse) ProtoMessage()    {}
func (*QueryProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69a11bcea5c6b00, []int{7}
}
func (m *QueryProfilesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProfilesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProfilesResponse.Merge(m, src)
}
func (m *QueryProfilesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProfilesResponse proto.InternalMessageInfo

func (m *QueryProfilesResponse) GetProfiles() []*QueryProfileResponse {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func (m *QueryProfilesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mirage.core.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mirage.core.v1.QueryParamsResponse")
	proto.RegisterType((*QueryDifficultyRequest)(nil), "mirage.core.v1.QueryDifficultyRequest")
	proto.RegisterType((*QueryDifficultyResponse)(nil), "mirage.core.v1.QueryDifficultyResponse")
	proto.RegisterType((*QueryProfileRequest)(nil), "mirage.core.v1.QueryProfileRequest")
	proto.RegisterType((*QueryProfileResponse)(nil), "mirage.core.v1.QueryProfileResponse")
	proto.RegisterType((*QueryProfilesRequest)(nil), "mirage.core.v1.QueryProfilesRequest")
	proto.RegisterType((*QueryProfilesResponse)(nil), "mirage.core.v1.QueryProfilesResponse")
}

func init() { proto.RegisterFile("mirage/core/v1/query.proto", fileDescriptor_c69a11bcea5c6b00) }

var fileDescriptor_c69a11bcea5c6b00 = []byte{
	// 972 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xae, 0x9b, 0x36, 0x4d, 0xa6, 0x5f, 0xdb, 0x69, 0xb7, 0x58, 0xa1, 0x84, 0xac, 0xcb, 0x6e,
	0x43, 0xc5, 0xc6, 0x6a, 0x39, 0x71, 0x83, 0x2e, 0x2c, 0x7b, 0x60, 0xa5, 0x62, 0xb1, 0x17, 0x0e,
	0x58, 0x13, 0xe7, 0x8d, 0x33, 0xc2, 0xf1, 0xb8, 0x33, 0xe3, 0x64, 0x23, 0x84, 0x10, 0xfc, 0x02,
	0x24, 0xfe, 0x01, 0x27, 0x8e, 0xfc, 0x8c, 0x3d, 0xae, 0xd4, 0x0b, 0xe2, 0x80, 0x50, 0x8b, 0xc4,
	0x7f, 0xe0, 0x84, 0xe6, 0xc3, 0x89, 0xd3, 0x96, 0x96, 0x4b, 0xe4, 0x79, 0x9e, 0xe7, 0xfd, 0x98,
	0x77, 0x5e, 0x3d, 0x41, 0x8d, 0x21, 0xe5, 0x24, 0x06, 0x3f, 0x62, 0x1c, 0xfc, 0xd1, 0x91, 0x7f,
	0x96, 0x03, 0x9f, 0x74, 0x32, 0xce, 0x24, 0xc3, 0x1b, 0x86, 0xeb, 0x28, 0xae, 0x33, 0x3a, 0x6a,
	0x6c, 0x91, 0x21, 0x4d, 0x99, 0xaf, 0x7f, 0x8d, 0xa4, 0xb1, 0x13, 0xb3, 0x98, 0xe9, 0x4f, 0x5f,
	0x7d, 0x59, 0x74, 0x2f, 0x66, 0x2c, 0x4e, 0xc0, 0x27, 0x19, 0xf5, 0x49, 0x9a, 0x32, 0x49, 0x24,
	0x65, 0xa9, 0xb0, 0xec, 0x61, 0xc4, 0xc4, 0x90, 0x09, 0xbf, 0x4b, 0x04, 0x98, 0x7a, 0xfe, 0xe8,
	0xa8, 0x0b, 0x92, 0x1c, 0xf9, 0x19, 0x89, 0x69, 0xaa, 0xc5, 0x56, 0xfb, 0xe6, 0x95, 0xf6, 0x32,
	0xc2, 0xc9, 0xd0, 0x26, 0xf2, 0x76, 0x10, 0xfe, 0x5c, 0x85, 0x9f, 0x6a, 0x30, 0x80, 0xb3, 0x1c,
	0x84, 0xf4, 0x4e, 0xd1, 0xf6, 0x1c, 0x2a, 0x32, 0x96, 0x0a, 0xc0, 0x1f, 0xa0, 0xaa, 0x09, 0x76,
	0x9d, 0x96, 0xd3, 0x5e, 0x3d, 0xde, 0xed, 0xcc, 0xdf, 0xae, 0x63, 0xf4, 0x27, 0xf5, 0x57, 0x7f,
	0xbc, 0xbd, 0xf0, 0xcb, 0xdf, 0xbf, 0x1e, 0x3a, 0x81, 0x0d, 0xf0, 0x5c, 0xb4, 0xab, 0x33, 0x7e,
	0x4c, 0xfb, 0x7d, 0x1a, 0xe5, 0x89, 0x9c, 0x14, 0xb5, 0x7e, 0x5f, 0x44, 0x6f, 0x5c, 0xa3, 0x6c,
	0xc1, 0xc7, 0x08, 0x47, 0x39, 0xe7, 0x90, 0xca, 0xb0, 0x37, 0x65, 0x75, 0xf1, 0xa5, 0x60, 0xcb,
	0x32, 0xb3, 0x30, 0xec, 0xa3, 0xed, 0x8c, 0xc3, 0x88, 0xb2, 0x5c, 0x94, 0xf5, 0x8b, 0x5a, 0x8f,
	0x0b, 0xaa, 0x14, 0xf0, 0x1e, 0xc2, 0x09, 0x11, 0x32, 0x8c, 0x06, 0x24, 0x8d, 0x21, 0x1c, 0x00,
	0x8d, 0x07, 0xd2, 0xad, 0xb4, 0x9c, 0x76, 0x25, 0xb8, 0xa7, 0x98, 0x27, 0x9a, 0x78, 0xa6, 0x71,
	0x7c, 0x88, 0xb6, 0x32, 0x36, 0x0e, 0x87, 0x20, 0x04, 0x89, 0x21, 0x8c, 0x58, 0x9e, 0x4a, 0x77,
	0x49, 0x27, 0xdf, 0xcc, 0xd8, 0xf8, 0xb9, 0xc1, 0x9f, 0x28, 0x18, 0x1f, 0xa3, 0xfb, 0x91, 0xba,
	0x42, 0x94, 0x4b, 0x3a, 0x82, 0x30, 0x61, 0xe3, 0x30, 0x57, 0xac, 0xbb, 0xac, 0xf5, 0xdb, 0x25,
	0xf2, 0x33, 0x36, 0x7e, 0xa1, 0x28, 0x95, 0x3f, 0x21, 0x12, 0x84, 0x0c, 0xbb, 0x09, 0x8b, 0xbe,
	0x0e, 0x07, 0x44, 0x0c, 0xdc, 0x6a, 0xcb, 0x69, 0xd7, 0x83, 0x4d, 0x43, 0x9c, 0x28, 0xfc, 0x19,
	0x11, 0x03, 0xfc, 0x10, 0x6d, 0x14, 0x93, 0xb1, 0x5d, 0xaf, 0xe8, 0xae, 0xd7, 0x2d, 0x6a, 0x5a,
	0xf6, 0xfc, 0xe2, 0x21, 0x39, 0xeb, 0xd3, 0x04, 0xec, 0xcc, 0xb1, 0x8b, 0x56, 0x48, 0xaf, 0xc7,
	0x41, 0x98, 0x97, 0xac, 0x07, 0xc5, 0xd1, 0x3b, 0x5f, 0x42, 0x3b, 0xf3, 0x11, 0xf6, 0x29, 0x76,
	0xd0, 0x32, 0x1b, 0xa7, 0xc0, 0x6d, 0x80, 0x39, 0xe0, 0x06, 0xaa, 0xe5, 0x02, 0x78, 0x4a, 0x86,
	0xa0, 0xc7, 0x5c, 0x0f, 0xa6, 0x67, 0x15, 0x91, 0xc0, 0x08, 0x12, 0x3d, 0xcf, 0xe5, 0xc0, 0x1c,
	0xf0, 0x5b, 0x08, 0x45, 0x1c, 0x88, 0x84, 0x5e, 0x48, 0xcc, 0xf4, 0x2a, 0x41, 0xdd, 0x22, 0x1f,
	0x49, 0xf5, 0x84, 0x22, 0xef, 0x8a, 0x88, 0xd3, 0x4c, 0xad, 0x70, 0x08, 0x2f, 0x33, 0xca, 0x27,
	0x7a, 0x6a, 0x95, 0x00, 0x97, 0xa9, 0x4f, 0x34, 0xa3, 0xf2, 0x91, 0x5c, 0xb2, 0x90, 0x43, 0x0a,
	0x63, 0x3d, 0xad, 0x5a, 0x50, 0x57, 0x48, 0xa0, 0x00, 0xbc, 0x8f, 0xd6, 0x39, 0x08, 0xe0, 0x23,
	0x08, 0xfb, 0x79, 0xda, 0x13, 0x7a, 0x4c, 0x4b, 0xc1, 0x9a, 0x05, 0x9f, 0x2a, 0x0c, 0x3f, 0x40,
	0x6b, 0x54, 0x84, 0x43, 0xd6, 0x03, 0x4e, 0x24, 0xe3, 0x6e, 0x4d, 0x67, 0x59, 0xa5, 0xe2, 0x79,
	0x01, 0xe1, 0x3d, 0x54, 0xef, 0x52, 0x16, 0x73, 0x92, 0x0d, 0x26, 0x6e, 0x5d, 0xdf, 0x74, 0x06,
	0xe0, 0x5d, 0x54, 0x25, 0x23, 0x22, 0x09, 0x77, 0x91, 0xa6, 0xec, 0x49, 0xe1, 0x5d, 0x92, 0xaa,
	0xa9, 0xad, 0x1a, 0xdc, 0x9c, 0xd4, 0x2d, 0xfb, 0x2c, 0x49, 0xd8, 0x18, 0x7a, 0xb3, 0xb2, 0xc2,
	0x5d, 0x6b, 0x55, 0xda, 0xf5, 0x00, 0x17, 0xd4, 0xb4, 0xba, 0x50, 0xcf, 0x3d, 0x0d, 0x50, 0x03,
	0x16, 0xee, 0xba, 0xd6, 0xae, 0x17, 0xe8, 0x0b, 0x05, 0xe2, 0x03, 0xb4, 0x39, 0x95, 0x49, 0x96,
	0xd1, 0x48, 0xb8, 0x1b, 0x5a, 0x37, 0x8d, 0xfe, 0x42, 0xa3, 0x6a, 0x2c, 0x7a, 0xc7, 0xa6, 0xe9,
	0x36, 0xb5, 0x6c, 0xcd, 0x82, 0x26, 0x5b, 0x49, 0x94, 0x31, 0x21, 0x85, 0x7b, 0x6f, 0x4e, 0x74,
	0xaa, 0x30, 0x25, 0x3a, 0xcb, 0x49, 0x42, 0xe5, 0xc4, 0x8a, 0xb6, 0x8c, 0xc8, 0x82, 0x5a, 0xe4,
	0x7d, 0x35, 0xbf, 0x54, 0x85, 0xcf, 0xe0, 0xa7, 0x08, 0xcd, 0xec, 0xca, 0x9a, 0xca, 0xa3, 0x8e,
	0xf1, 0xb6, 0x8e, 0xf2, 0xb6, 0x8e, 0xf1, 0x52, 0xeb, 0x6d, 0x9d, 0x53, 0x12, 0x17, 0x3b, 0x1c,
	0x94, 0x22, 0xbd, 0x9f, 0x1d, 0x74, 0xff, 0x4a, 0x01, 0xbb, 0xb6, 0x1f, 0xa2, 0x5a, 0x66, 0x31,
	0xd7, 0x69, 0x55, 0xda, 0xab, 0xc7, 0xef, 0x5c, 0x35, 0xad, 0x9b, 0xd6, 0x3d, 0x98, 0x46, 0xe1,
	0x4f, 0xe7, 0x7a, 0x5c, 0xd4, 0x3d, 0x1e, 0xdc, 0xd9, 0xa3, 0x4d, 0x53, 0x0a, 0x3d, 0xfe, 0xa7,
	0x82, 0x96, 0x75, 0x2d, 0x7c, 0x86, 0xaa, 0xc6, 0x29, 0xb1, 0x77, 0x73, 0x33, 0x65, 0x33, 0x6e,
	0xec, 0xdf, 0xaa, 0x31, 0x85, 0xbc, 0xe6, 0x0f, 0xe7, 0x7f, 0xfd, 0xb4, 0xe8, 0xe2, 0x5d, 0xff,
	0x46, 0xb7, 0xc7, 0xdf, 0x3b, 0x08, 0x95, 0x8c, 0xef, 0xd1, 0x8d, 0x39, 0xaf, 0x99, 0x73, 0xe3,
	0xe0, 0x4e, 0x9d, 0xad, 0xef, 0xe9, 0xfa, 0x7b, 0xb8, 0x71, 0xb5, 0xfe, 0xcc, 0x87, 0xf1, 0x77,
	0x68, 0xc5, 0x8e, 0x19, 0xef, 0xdf, 0xfe, 0x08, 0xa6, 0xf8, 0xff, 0x7a, 0x29, 0xef, 0x5d, 0x5d,
	0x79, 0x1f, 0x3f, 0xb8, 0x76, 0x73, 0x23, 0xf4, 0xbf, 0xb1, 0xde, 0xf6, 0x2d, 0x9e, 0xa0, 0x5a,
	0xb1, 0x20, 0xf8, 0xd6, 0xe4, 0xd3, 0xd9, 0x3f, 0xbc, 0x43, 0x65, 0x7b, 0x68, 0xe9, 0x1e, 0x1a,
	0xd8, 0xfd, 0x8f, 0x1e, 0xc4, 0xc9, 0xe3, 0x57, 0x17, 0x4d, 0xe7, 0xf5, 0x45, 0xd3, 0xf9, 0xf3,
	0xa2, 0xe9, 0xfc, 0x78, 0xd9, 0x5c, 0x78, 0x7d, 0xd9, 0x5c, 0xf8, 0xed, 0xb2, 0xb9, 0xf0, 0xe5,
	0xb6, 0x0d, 0x79, 0x69, 0x82, 0xe4, 0x24, 0x03, 0xd1, 0xad, 0xea, 0x7f, 0xe7, 0xf7, 0xff, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xa8, 0x8c, 0xae, 0x5e, 0x5b, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Difficulty queries the current PoW difficulty state.
	Difficulty(ctx context.Context, in *QueryDifficultyRequest, opts ...grpc.CallOption) (*QueryDifficultyResponse, error)
	// Profile queries a profile by address.
	Profile(ctx context.Context, in *QueryProfileRequest, opts ...grpc.CallOption) (*QueryProfileResponse, error)
	// Profiles queries all profiles with pagination.
	Profiles(ctx context.Context, in *QueryProfilesRequest, opts ...grpc.CallOption) (*QueryProfilesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mirage.core.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Difficulty(ctx context.Context, in *QueryDifficultyRequest, opts ...grpc.CallOption) (*QueryDifficultyResponse, error) {
	out := new(QueryDifficultyResponse)
	err := c.cc.Invoke(ctx, "/mirage.core.v1.Query/Difficulty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Profile(ctx context.Context, in *QueryProfileRequest, opts ...grpc.CallOption) (*QueryProfileResponse, error) {
	out := new(QueryProfileResponse)
	err := c.cc.Invoke(ctx, "/mirage.core.v1.Query/Profile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Profiles(ctx context.Context, in *QueryProfilesRequest, opts ...grpc.CallOption) (*QueryProfilesResponse, error) {
	out := new(QueryProfilesResponse)
	err := c.cc.Invoke(ctx, "/mirage.core.v1.Query/Profiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Difficulty queries the current PoW difficulty state.
	Difficulty(context.Context, *QueryDifficultyRequest) (*QueryDifficultyResponse, error)
	// Profile queries a profile by address.
	Profile(context.Context, *QueryProfileRequest) (*QueryProfileResponse, error)
	// Profiles queries all profiles with pagination.
	Profiles(context.Context, *QueryProfilesRequest) (*QueryProfilesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Difficulty(ctx context.Context, req *QueryDifficultyRequest) (*QueryDifficultyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Difficulty not implemented")
}
func (*UnimplementedQueryServer) Profile(ctx context.Context, req *QueryProfileRequest) (*QueryProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Profile not implemented")
}
func (*UnimplementedQueryServer) Profiles(ctx context.Context, req *QueryProfilesRequest) (*QueryProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Profiles not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mirage.core.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Difficulty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDifficultyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Difficulty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mirage.core.v1.Query/Difficulty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Difficulty(ctx, req.(*QueryDifficultyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mirage.core.v1.Query/Profile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Profile(ctx, req.(*QueryProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Profiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Profiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mirage.core.v1.Query/Profiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Profiles(ctx, req.(*QueryProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mirage.core.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Difficulty",
			Handler:    _Query_Difficulty_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _Query_Profile_Handler,
		},
		{
			MethodName: "Profiles",
			Handler:    _Query_Profiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mirage/core/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryDifficultyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDifficultyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDifficultyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDifficultyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDifficultyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDifficultyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CurrentHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.LatestBlockHash) > 0 {
		i -= len(m.LatestBlockHash)
		copy(dAtA[i:], m.LatestBlockHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.LatestBlockHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.ConsecutiveLowUsage != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ConsecutiveLowUsage))
		i--
		dAtA[i] = 0x28
	}
	if m.PowMessageCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PowMessageCount))
		i--
		dAtA[i] = 0x20
	}
	if m.LastChangeHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LastChangeHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.PreviousDifficulty != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PreviousDifficulty))
		i--
		dAtA[i] = 0x10
	}
	if m.CurrentDifficulty != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CurrentDifficulty))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryProfileRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProfileRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProfileRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProfileResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProfileResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProfileResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.QualityPosts) > 0 {
		for iNdEx := len(m.QualityPosts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.QualityPosts[iNdEx])
			copy(dAtA[i:], m.QualityPosts[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.QualityPosts[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	}
	if len(m.BlockedPosts) > 0 {
		for iNdEx := len(m.BlockedPosts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BlockedPosts[iNdEx])
			copy(dAtA[i:], m.BlockedPosts[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.BlockedPosts[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if len(m.BlockedUsers) > 0 {
		for iNdEx := len(m.BlockedUsers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BlockedUsers[iNdEx])
			copy(dAtA[i:], m.BlockedUsers[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.BlockedUsers[iNdEx])))
			i--
			dAtA[i] = 0x7a
		}
	}
	if len(m.FollowedTopics) > 0 {
		for iNdEx := len(m.FollowedTopics) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FollowedTopics[iNdEx])
			copy(dAtA[i:], m.FollowedTopics[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.FollowedTopics[iNdEx])))
			i--
			dAtA[i] = 0x72
		}
	}
	if len(m.FollowedUsers) > 0 {
		for iNdEx := len(m.FollowedUsers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FollowedUsers[iNdEx])
			copy(dAtA[i:], m.FollowedUsers[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.FollowedUsers[iNdEx])))
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.FollowedModerators) > 0 {
		for iNdEx := len(m.FollowedModerators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FollowedModerators[iNdEx])
			copy(dAtA[i:], m.FollowedModerators[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.FollowedModerators[iNdEx])))
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.Banner) > 0 {
		i -= len(m.Banner)
		copy(dAtA[i:], m.Banner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Banner)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Avatar) > 0 {
		i -= len(m.Avatar)
		copy(dAtA[i:], m.Avatar)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Avatar)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Biography) > 0 {
		i -= len(m.Biography)
		copy(dAtA[i:], m.Biography)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Biography)))
		i--
		dAtA[i] = 0x4a
	}
	if m.IsModerator {
		i--
		if m.IsModerator {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.ReserveFunds != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ReserveFunds))
		i--
		dAtA[i] = 0x38
	}
	if m.AutoRenew {
		i--
		if m.AutoRenew {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.SubscriptionExpiry != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.SubscriptionExpiry))
		i--
		dAtA[i] = 0x28
	}
	if m.CreatedAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	if m.Level != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Level))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProfilesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProfilesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProfilesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProfilesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProfilesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProfilesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Profiles) > 0 {
		for iNdEx := len(m.Profiles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Profiles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDifficultyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDifficultyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CurrentDifficulty != 0 {
		n += 1 + sovQuery(uint64(m.CurrentDifficulty))
	}
	if m.PreviousDifficulty != 0 {
		n += 1 + sovQuery(uint64(m.PreviousDifficulty))
	}
	if m.LastChangeHeight != 0 {
		n += 1 + sovQuery(uint64(m.LastChangeHeight))
	}
	if m.PowMessageCount != 0 {
		n += 1 + sovQuery(uint64(m.PowMessageCount))
	}
	if m.ConsecutiveLowUsage != 0 {
		n += 1 + sovQuery(uint64(m.ConsecutiveLowUsage))
	}
	l = len(m.LatestBlockHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.CurrentHeight != 0 {
		n += 1 + sovQuery(uint64(m.CurrentHeight))
	}
	return n
}

func (m *QueryProfileRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryProfileResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Level != 0 {
		n += 1 + sovQuery(uint64(m.Level))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovQuery(uint64(m.CreatedAt))
	}
	if m.SubscriptionExpiry != 0 {
		n += 1 + sovQuery(uint64(m.SubscriptionExpiry))
	}
	if m.AutoRenew {
		n += 2
	}
	if m.ReserveFunds != 0 {
		n += 1 + sovQuery(uint64(m.ReserveFunds))
	}
	if m.IsModerator {
		n += 2
	}
	l = len(m.Biography)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Banner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.FollowedModerators) > 0 {
		for _, s := range m.FollowedModerators {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.FollowedUsers) > 0 {
		for _, s := range m.FollowedUsers {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.FollowedTopics) > 0 {
		for _, s := range m.FollowedTopics {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.BlockedUsers) > 0 {
		for _, s := range m.BlockedUsers {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.BlockedPosts) > 0 {
		for _, s := range m.BlockedPosts {
			l = len(s)
			n += 2 + l + sovQuery(uint64(l))
		}
	}
	if len(m.QualityPosts) > 0 {
		for _, s := range m.QualityPosts {
			l = len(s)
			n += 2 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryProfilesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryProfilesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Profiles) > 0 {
		for _, e := range m.Profiles {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDifficultyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDifficultyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDifficultyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDifficultyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDifficultyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDifficultyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentDifficulty", wireType)
			}
			m.CurrentDifficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentDifficulty |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousDifficulty", wireType)
			}
			m.PreviousDifficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviousDifficulty |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastChangeHeight", wireType)
			}
			m.LastChangeHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastChangeHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowMessageCount", wireType)
			}
			m.PowMessageCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PowMessageCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsecutiveLowUsage", wireType)
			}
			m.ConsecutiveLowUsage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsecutiveLowUsage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestBlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestBlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentHeight", wireType)
			}
			m.CurrentHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProfileRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProfileRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProfileRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProfileResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProfileResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProfileResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			m.Level = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionExpiry", wireType)
			}
			m.SubscriptionExpiry = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionExpiry |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoRenew", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AutoRenew = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveFunds", wireType)
			}
			m.ReserveFunds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReserveFunds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsModerator", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsModerator = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Biography", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Biography = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Banner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Banner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FollowedModerators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FollowedModerators = append(m.FollowedModerators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FollowedUsers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FollowedUsers = append(m.FollowedUsers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FollowedTopics", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FollowedTopics = append(m.FollowedTopics, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockedUsers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockedUsers = append(m.BlockedUsers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockedPosts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockedPosts = append(m.BlockedPosts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QualityPosts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QualityPosts = append(m.QualityPosts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProfilesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProfilesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProfilesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProfilesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProfilesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProfilesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Profiles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Profiles = append(m.Profiles, &QueryProfileResponse{})
			if err := m.Profiles[len(m.Profiles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
